# جریان کاری RNA-seq: تحلیل اکتشافی در سطح ژن و differential expression analysis (تحلیل بیان تفاضلی)

Michael I. Love 1,2 ، Simon Anders 3 ، Vladislav Kim 4 و Wolfgang Huber 4

1 گروه آمارزیستی، UNC-Chapel Hill، چپل‌هیل، کارولینای شمالی، آمریکا  
2 گروه ژنتیک، UNC-Chapel Hill، چپل‌هیل، کارولینای شمالی، آمریکا  
3 مرکز زیست‌شناسی مولکولی دانشگاه هایدلبرگ، هایدلبرگ، آلمان  
4 آزمایشگاه اروپایی زیست‌شناسی مولکولی (EMBL)، هایدلبرگ، آلمان

#### ۱۶ اکتبر ۲۰۱۹

#### چکیده

در اینجا گام‌به‌گام یک جریان کاری انتهابه‌انتها برای RNA-seq در سطح ژن برای انجام differential expression analysis (تحلیل بیان تفاضلی) در سطح ژن با استفاده از بسته‌های Bioconductor مرور می‌کنیم. از فایل‌های FASTQ آغاز می‌کنیم، نشان می‌دهیم چگونه این داده‌ها نسبت به transcripts (رونوشت‌ها)ی مرجع کمی‌سازی شده‌اند، و مجموعه‌داده‌های count (شمارش) در سطح ژن را برای تحلیل‌های پایین‌دستی آماده می‌کنیم. exploratory data analysis (تحلیل اکتشافی داده‌ها؛ EDA) را برای ارزیابی کیفیت و بررسی ارتباط بین نمونه‌ها انجام می‌دهیم، تحلیل بیان تفاضلی ژنی را پیش می‌بریم، و نتایج را به‌صورت بصری بررسی می‌کنیم.

# فهرست مطالب

* 1 مقدمه
  
    + 1\.1 داده‌های آزمایشی
* 2 آماده‌سازی ورودی کمی‌سازی برای _DESeq2_
  
    + 2\.1 کمی‌سازی رونوشت و _tximport_ / _tximeta_
    + 2\.2 کمی‌سازی با _Salmon_
    + 2\.3 خواندن داده با _tximeta_
    + 2\.4 توابع واردسازی _DESeq2_
    + 2\.5 _SummarizedExperiment_
    + 2\.6 نقطهٔ انشعاب
* 3 شیء _DESeqDataSet_، اطلاعات نمونه و فرمول طراحی
  
    + 3\.1 شروع از _SummarizedExperiment_
    + 3\.2 شروع از ماتریس‌های شمارش
* 4 تحلیل اکتشافی و بصری‌سازی
  
    + 4\.1 پیش‌پالایش مجموعه‌داده
    + 4\.2 تبدیل پایاساز واریانس و rlog
    + 4\.3 فاصله‌های نمونه
    + 4\.4 نمودار PCA
    + 4\.5 نمودار PCA با استفاده از PCA تعمیم‌یافته
    + 4\.6 نمودار MDS
* 5 تحلیل بیان تفاضلی
  
    + 5\.1 اجرای خط لولهٔ تحلیل بیان تفاضلی
    + 5\.2 ساخت جدول نتایج
    + 5\.3 مقایسه‌های دیگر
    + 5\.4 multiple testing (آزمون‌های چندگانه)
* 6 ترسیم نتایج
  
    + 6\.1 نمودار شمارش‌ها
    + 6\.2 MA-plot
    + 6\.3 خوشه‌بندی ژن
    + 6\.4 پالایش مستقل
    + 6\.5 Independent Hypothesis Weighting
* 7 حاشیه‌نویسی و برون‌داد نتایج
  
    + 7\.1 برون‌داد نتایج
    + 7\.2 ترسیم تغییرِ نسبت‌ها در فضای ژنومی
* 8 حذف batch effects (اثرهای دسته‌ای) نهفته
  
    + 8\.1 استفاده از SVA با DESeq2
    + 8\.2 استفاده از RUV با DESeq2
* 9 آزمایش‌های گذر زمان
* 10 پیوست
  
    + 10\.1 جزئیات به‌روز دربارهٔ کمی‌سازی
        
        - 10\.1.1 دانلود فایل‌های FASTQ
        - 10\.1.2 ساخت ایندکس salmon
        - 10\.1.3 کمی‌سازی abundance (فراوانی) با salmon
        - 10\.1.4 تولید یک RangedSummarizedExperiment با tximeta
* 11 اطلاعات نشست
* منابع

**نسخهٔ R** : R version 4.6.0 RC (2026-04-17 r89917)

**نسخهٔ Bioconductor** : 3.23

**بسته** : 1.36.0

# 1 مقدمه

Bioconductor مجموعهٔ بزرگی از بسته‌ها را برای تحلیل داده‌های توالی‌یابی پربازده، از جمله RNA-seq، پشتیبانی می‌کند. بسته‌هایی که در این جریان کاری استفاده می‌کنیم شامل بسته‌های هسته‌ایِ نگه‌داری‌شده توسط تیم هستهٔ Bioconductor برای کار با حاشیه‌نویسی‌های ژنی هستند (مکان‌های gene (ژن) و transcript (رونوشت) در ژنوم، و نیز بازیابی شناسهٔ ژن). همچنین از بسته‌های مشارکتی برای تحلیل‌های آماری و بصری‌سازی داده‌های توالی‌یابی بهره می‌گیریم. با انتشارهای زمان‌بندی‌شدهٔ هر ۶ ماه، پروژهٔ Bioconductor اطمینان می‌دهد که همهٔ بسته‌های درون یک انتشار با هم سازگار و هماهنگ کار می‌کنند (و از این‌رو استعارهٔ «رسانه/رهبر ارکستر»). بسته‌های استفاده‌شده در این جریان کاری با تابع _library_ بارگذاری می‌شوند و می‌توان آن‌ها را با دنبال کردن [راهنمای نصب بسته‌های Bioconductor](http://bioconductor.org/install/) نصب کرد.

* نسخهٔ منتشرشدهٔ این جریان کاری، شامل گزارش‌های داوران و دیدگاه‌ها، در [F1000Research](http://f1000research.com/articles/4-1070) در دسترس است. نسخه‌ای که اکنون می‌خوانید با آن متفاوت است، به‌ویژه از این جهت که اینجا کد اجرای سریع **transcript quantification (کمی‌سازی رونوشت)** و سپس واردسازی در R/Bioconductor برای انجام تحلیل در سطح ژن را ارائه می‌کنیم.
* جریان کاری Bioconductor دیگری که **differential transcript usage (DTU)** را پوشش می‌دهد، جریان کاری [rnaseqDTU](https://bioconductor.org/packages/rnaseqDTU) است؛ نسخهٔ منتشرشدهٔ آن نیز در [F1000Research](https://f1000research.com/articles/7-952/v3) در دسترس است.
* اگر دربارهٔ این جریان کاری یا هر نرم‌افزار Bioconductor پرسشی دارید، آن را در [Bioconductor support site](https://support.bioconductor.org/) مطرح کنید. اگر پرسش به بسته‌ای مشخص مربوط است، می‌توانید پست را با نام آن بسته برچسب بزنید، و برای پرسش‌های کلی‌تر دربارهٔ جریان کاری، پست را با `rnaseqgene` برچسب بزنید. جهت طرح پرسشی بهینه در سایت پشتیبانی، [راهنمای ارسال](http://www.bioconductor.org/help/support/posting-guide/) را ببینید.

## ۱٫۱ داده‌های آزمایشی

داده‌های به‌کاررفته در این جریان کاری در بستهٔ _[airway](https://bioconductor.org/packages/3.23/airway)_ ذخیره شده‌اند که خلاصه‌ای از یک آزمایش RNA-seq است؛ در آن، سلول‌های ماهیچهٔ صاف مجاری تنفسی با دگزامتازون، یک گلوکوکورتیکوئید صناعی با اثرات ضدالتهابی، تیمار شده‌اند (Himes و همکاران 2014). گلوکوکورتیکوئیدها، برای نمونه، توسط بیماران آسمی برای کاهش التهاب راه‌های هوایی استفاده می‌شوند. در این آزمایش، چهار رده‌سلولی اولیهٔ انسانی از ماهیچهٔ صاف مجاری با ۱ میکرومولار دگزامتازون به‌مدت ۱۸ ساعت تیمار شدند. برای هر یک از این چهار رده‌سلولی، یک نمونهٔ تیمارشده و یک نمونهٔ تیمارنشده داریم. برای توضیحات بیشتر دربارهٔ آزمایش به [مدخل PubMed 24926665](http://www.ncbi.nlm.nih.gov/pubmed/24926665) و برای دادهٔ خام به [مدخل GEO GSE52778](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52778) مراجعه کنید.

# 2 آماده‌سازی ورودی کمی‌سازی برای DESeq2

برای ورودی، روش‌های آماریِ مبتنی بر count (شمارش)، مانند _[DESeq2](https://bioconductor.org/packages/3.23/DESeq2)_ (Love، Huber و Anders 2014)، _[edgeR](https://bioconductor.org/packages/3.23/edgeR)_ (Robinson، McCarthy و Smyth 2009)، _[limma](https://bioconductor.org/packages/3.23/limma)_ با روش voom (Law و همکاران 2014)، _[DSS](https://bioconductor.org/packages/3.23/DSS)_ (Wu، Wang و Wu 2013)، _[EBSeq](https://bioconductor.org/packages/3.23/EBSeq)_ (Leng و همکاران 2013) و _[baySeq](https://bioconductor.org/packages/3.23/baySeq)_ (Hardcastle و Kelly 2010)، انتظار دارند دادهٔ ورودی، مثلاً از RNA-seq یا هر آزمایش توالی‌یابی پربازده دیگر، به‌صورت ماتریسی از شمارش‌های نرمال‌سازی‌نشده باشد. مقدار خانهٔ واقع در ردیف _i_ ام و ستون _j_ ام ماتریس نشان می‌دهد چند reads (خوانش)‌ (یا قطعه، برای RNA-seq دوسر) می‌توان به gene (ژن) _i_ در نمونهٔ _j_ نسبت داد. به‌طور مشابه، برای انواع دیگر آزمون‌ها، ردیف‌های ماتریس ممکن است متناظر با نواحی اتصال (در ChIP-Seq)، یا توالی‌های پپتیدی (در طیف‌سنجی جرمی کمی) باشند.

مقادیر در ماتریس باید شمارش‌ها یا شمارش‌های برآوردشدهٔ خوانش‌ها/قطعه‌های توالی‌یابی باشند. این موضوع برای برقرار بودن مدل آماری _DESeq2_ مهم است، زیرا تنها شمارش‌ها امکان برآوردِ ...
تا دقت اندازه‌گیری را به‌درستی بازتاب دهد. بسیار مهم است که _هرگز_ count (شمارش)‌هایی را که از پیش برای عمق توالی‌یابی/اندازهٔ کتابخانهٔ نمونه normalization (نرمال‌سازی) شده‌اند ارائه نکنید؛ زیرا مدل آماری زمانی بیشترین توان را دارد که بر شمارش‌های نانرمال‌شده اعمال شود و به‌طور درون‌مدل برای اختلاف اندازهٔ کتابخانه‌ها نیز طراحی شده است.

## ۲٫۱ کمی‌سازی رونوشت‌ها با _tximport_ / _tximeta_

در نسخهٔ پیشین این جریان‌کار (از جمله نسخهٔ منتشرشده) نشان داده شد که چگونه می‌توان read (خوانش)‌ها را به ژنوم هم‌تراز کرد و سپس تعداد خوانش‌هایی را شمرد که با الگوهای gene (ژن) سازگارند. اکنون یک خط لولهٔ جایگزین و سریع‌تر به‌جای هم‌ترازی ژنومی و شمارش خوانش‌ها توصیه می‌شود. در این جریان‌کار نشان خواهیم داد چگونه داده‌های کمی‌سازی سطح transcript (رونوشت) را وارد کرده و با استفاده از _tximport_ یا _tximeta_ به سطح ژن تجمیع کنیم. روش‌های کمی‌سازی رونوشت مانند [Salmon](https://combine-lab.github.io/salmon/) (Patro et al. 2017 ) ، [kallisto](https://pachterlab.github.io/kallisto/) (Bray et al. 2016 ) یا [RSEM](http://deweylab.github.io/RSEM/) (Li and Dewey 2011 ) نگاشت یا هم‌ترازی خوانش‌ها به رونوشت‌های مرجع را انجام می‌دهند و در خروجی، شمارش‌های برآوردشده برای هر رونوشت و نیز طول‌های مؤثر رونوشت را می‌دهند که اثرات بایاس را خلاصه می‌کنند. پس از اجرای یکی از این ابزارها، بسته‌های _[tximport](https://bioconductor.org/packages/3.23/tximport)_ (Soneson, Love, and Robinson 2015 ) یا _[tximeta](https://bioconductor.org/packages/3.23/tximeta)_ (Love et al. 2020 ) می‌توانند ماتریس‌های شمارش و offset (افست) برآوردشده را برای استفاده در بسته‌های Bioconductor مربوط به differential expression analysis (تحلیل بیان تفاضلی) ژن‌ها بسازند؛ همان‌گونه که در ادامه نشان داده خواهد شد.

آموزشی کوتاه دربارهٔ استفاده از نرم‌افزار _Salmon_ برای کمی‌سازی abundance (فراوانی) رونوشت
[اینجا](https://combine-lab.github.io/salmon/getting_started/) در دسترس است.
توصیه می‌کنیم از `--gcBias` [flag](http://salmon.readthedocs.io/en/latest/salmon.html) استفاده کنید که یک ضریب تصحیح برای بایاس‌های نظام‌مند که به‌طور معمول در داده‌های RNA-seq وجود دارند برآورد می‌کند (Love, Hogenesch, and Irizarry 2016 ; Patro et al. 2017 ) ، مگر آن‌که مطمئن باشید داده‌های شما چنین بایاس‌هایی ندارند.

مزیت‌های استفاده از ابزارهای کمی‌سازی فراوانی رونوشت در کنار _tximport_ / _tximeta_ برای تولید ماتریس‌های شمارش در سطح ژن و افست‌های نرمال‌سازی عبارت‌اند از: (1) این رویکرد هرگونه تغییر احتمالی در طول ژن‌ها در میان نمونه‌ها را تصحیح می‌کند (مثلاً ناشی از استفادهٔ تفاضلی ایزوفرم‌ها) (Trapnell et al. 2013 ) ؛ (2) برخی از این روش‌ها به‌طور قابل‌توجهی سریع‌ترند و حافظه و دیسک کمتری نسبت به روش‌های مبتنی بر هم‌ترازی نیاز دارند؛ و (3) می‌توان از کنار گذاشتن آن دسته از قطعاتی که می‌توانند به چند ژن با توالی‌های همولوگ هم‌تراز شوند پرهیز کرد (Robert and Watson 5 201 ) . توجه داشته باشید که ابزارهای کمی‌سازی فراوانی رونوشت از تولید فایل‌های بزرگ حاوی هم‌ترازی خوانش‌ها صرف‌نظر می‌کنند و در عوض، فایل‌های کوچک‌تری تولید می‌کنند که فراوانی‌های برآوردشده، شمارش‌ها و طول‌های مؤثر به‌ازای هر رونوشت را ذخیره می‌کنند. برای جزئیات بیشتر، به دست‌نوشتهٔ تشریح‌کنندهٔ این رویکرد (Soneson, Love, and Robinson 2015 ) و وینگت بستهٔ _[tximport](https://bioconductor.org/packages/3.23/tximport)_ برای جزئیات نرم‌افزاری مراجعه کنید.

_[tximeta](https://bioconductor.org/packages/3.23/tximeta)_ (Love et al. 2020 ) گسترشی بر _tximport_ است که همان کارکردها را به‌همراه مزیت افزودهٔ افزودن خودکار فرادادهٔ شرح‌واره برای ترنسکریپتوم‌های پرتکرار (GENCODE، Ensembl، RefSeq برای انسان و موش) ارائه می‌دهد. برای جزئیات بیشتر، وینگت بستهٔ [tximeta vignette](https://bioconductor.org/packages/release/bioc/vignettes/tximeta/inst/doc/tximeta.htmlm) را ببینید. _tximeta_ یک _SummarizedExperiment_ تولید می‌کند که با استفاده از تابع `DESeqDataSet` به‌آسانی در _DESeq2_ بارگذاری می‌شود؛ که در ادامه نشان داده خواهد شد. همچنین دربارهٔ ورودی‌های ممکن به _DESeq2_ نیز گفتگو خواهیم کرد، چه با استفاده از _tximport_ ، _tximeta_ ، _htseq_ (Anders, Pyl, and Huber 2015 ) ، یا یک ماتریس شمارش از پیش محاسبه‌شده.

## ۲٫۲ کمی‌سازی با _Salmon_

همان‌گونه که در بالا اشاره شد، آموزشی کوتاه دربارهٔ نحوهٔ استفاده از _Salmon_ را می‌توان
[اینجا](https://combine-lab.github.io/salmon/getting_started/)
یافت؛ بنابراین در عوض، کدی را ارائه می‌کنیم که برای کمی‌سازی فایل‌های به‌کاررفته در این جریان‌کار استفاده شد. _Salmon_ را می‌توان به‌راحتی روی یک کلاستر با استفاده از
سیستم مدیریت جریان‌کار [Snakemake](https://snakemake.readthedocs.io/en/stable/) (Köster and Rahmann 2012 ) اجرا کرد.

`Snakemake` زیر برای کمی‌سازی هشت نمونه‌ای به‌کار رفت که از SRA دانلود شده بودند (شناسهٔ SRR همان شناسهٔ اجرا است، و برای این هشت نمونه، تنها یک اجرا به‌ازای هر نمونه وجود داشت).

```
DATASETS = ["SRR1039508",
            "SRR1039509",
            "SRR1039512",
            "SRR1039513",
            "SRR1039516",
            "SRR1039517",
            "SRR1039520",
            "SRR1039521"]

SALMON = "/path/to/salmon_0.14.1/bin/salmon"

rule all:
  input: expand("quants/{dataset}/quant.sf", dataset=DATASETS)

rule salmon_quant:
    input:
        r1 = "fastq/{sample}_1.fastq.gz",
        r2 = "fastq/{sample}_2.fastq.gz",
        index = "/path/to/gencode.v29_salmon_0.14.1"
    output:
        "quants/{sample}/quant.sf"
    params:
        dir = "quants/{sample}"
    shell:
        "{SALMON} quant -i {input.index} -l A -p 6 --validateMappings \
         --gcBias --numGibbsSamples 20 -o {params.dir} \
         -1 {input.r1} -2 {input.r2}"
```

خط آخر، خط کلیدی‌ای است که _Salmon_ را اجرا می‌کند. این خط می‌گوید با استفاده از یک نمایهٔ مشخص، با تشخیص خودکار نوع کتابخانه، با به‌کارگیری 6 ترد، با گزینهٔ validate mappings (این گزینه در نسخه‌های _Salmon_ \\(\\ge\\) 0\.99 پیش‌فرض است)، با تصحیح بایاس GC، و با نوشتن 20 نمونهٔ گیبس (این مورد اختیاری است) کمی‌سازی انجام شود. سه آرگومان پایانی، پوشهٔ خروجی و دو فایل خوانشِ جفت‌شده را مشخص می‌کنند.

فایل Snakemake فوق مستلزم آن است که یک نمایه در `/path/to/gencode.vVV_salmon_X.Y.Z` ساخته شود؛ جایی که VV و X,Y,Z باید به مشخص کردن ویرایش رونوشت‌های مرجع و نسخهٔ _Salmon_ کمک کنند.
برای رونوشت‌های مرجع انسان و موش، توصیه می‌کنیم از [GENCODE](https://gencodegenes.org/) (Frankish et al. 2018 ) استفاده شود.

نمایهٔ _Salmon_ را می‌توان به‌سادگی با دستور زیر ساخت:

```
salmon index -t transcripts.fa.gz -i name_of_index
```

**نکته:** _Salmon_ می‌تواند هنگام نمایه‌سازی از _decoy sequences_ (دنباله‌های دیکوی) نیز استفاده کند، همان‌گونه که در Srivastava et al. ( 2020 ) توصیف شده و نشان داده شده که دقت کمی‌سازی را بهبود می‌دهد. برای جزئیات بیشتر دربارهٔ نحوهٔ استفاده از دنباله‌های دیکوی در نرم‌افزار _Salmon_ لطفاً این یادداشت را در [Salmon documentation](https://salmon.readthedocs.io/en/latest/salmon.html) ببینید. در این‌جا، نگاشت خوانش‌ها به ترنسکریپتوم را بدون دنباله‌های دیکوی ادامه می‌دهیم. هنگام نمایه‌سازی، پیامی ظاهر خواهد شد مبنی بر این‌که نمایهٔ _Salmon_ بدون هیچ دنبالهٔ دیکویی ساخته می‌شود.

اگر رونوشت‌ها از GENCODE دانلود شده‌اند، توصیه می‌شود از دستوری مشابه دستور زیر استفاده شود (که صرفاً به حذف اطلاعات افزوده از نام رونوشت‌ها کمک می‌کند):

```
salmon index --gencode -t gencode.v29.transcripts.fa.gz \
  -i gencode.v29_salmon_X.Y.Z
```

فایل Snakemake فوق را می‌توان سپس به روش‌های مختلف [execute Snakemake](https://snakemake.readthedocs.io/en/stable/executing/cli.html) کرد، از جمله ارسال چندین کار به یک کلاستر محاسباتی یا در فضای ابری. فایل Snakemake فوق، پس از ویرایش برای بازتاب مسیرهای واقعی منابع، روی یک کلاستر با زمان‌بند SLURM اجرا شد، با خط زیر در یک کار جداگانه که به کلاستر ارسال شد:

```
snakemake -j 4 --latency-wait 30 --cluster "sbatch -N 1 -n 6"
```

این دستور فرض می‌کند که دستورالعمل‌های Snakemake در فایلی به نام «Snakefile» قرار دارند.
گزینه‌های استفاده‌شده در این‌جا شامل موارد زیر است:

* `-j` : حداکثر تعداد کارهایی که به‌صورت موازی اجرا می‌شوند
* `--latency-wait` : تعداد ثانیه‌های مجاز برای در دسترس شدن فایل جهت آغاز گام‌های بعدی، در صورت وجود تأخیر
* `--cluster` : [در readthedocs.io وجود ندارد؟]
* گزینهٔ «-s» را می‌توان برای اجرای snakemake روی فایلی با نام مشخص استفاده کرد («Snakefile» پیش‌فرض است)

## ۲٫۳ خواندن داده‌ها با _tximeta_

در ادامهٔ جریان‌کار، شیئی را بارگذاری خواهیم کرد که شامل
داده‌های کمی‌سازی در سطح gene (ژن) برای هر هشت نمونه. با این حال، بستهٔ _[airway](https://bioconductor.org/packages/3.23/airway)_ همچنین شامل دو پوشهٔ کمی‌سازیِ خروجی‌شده توسط _Salmon_ است تا نشان دهیم چگونه می‌توان این داده را در R/Bioconductor وارد کرد. برای کوچک‌تر نگه‌داشتن اندازهٔ بستهٔ داده، فایل‌های `quant.sf` در پوشه‌های کمی‌سازی فشرده‌سازی (gzip) شده‌اند؛ بنابراین در جاهایی که در ادامه `quant.sf.gz` می‌بینید، احتمالاً روی رایانهٔ خود از `quant.sf` استفاده خواهید کرد.

پس از نمایش واردسازی با _tximeta_، ماتریس کامل count (شمارش) متناظر با همهٔ نمونه‌ها و کل داده را که از پیش در همان بسته فراهم شده است بارگذاری می‌کنیم و تحلیل را با همان شیء دادهٔ کامل ادامه می‌دهیم.

ابتدا بستهٔ داده شامل دادهٔ نمونه را بارگذاری می‌کنیم:

```
library("airway")
```

تابع _system.file_ در R می‌تواند محل نصب فایل‌های یک بسته روی رایانهٔ شما را بیابد. در اینجا مسیر کامل پوشهٔ `extdata` را که محل نگهداری داده‌های خارجیِ بسته‌های R است و بخشی از بستهٔ _[airway](https://bioconductor.org/packages/3.23/airway)_ محسوب می‌شود، درخواست می‌کنیم.

```
dir <- system.file("extdata", package="airway", mustWork=TRUE)
```

در این پوشه، تعدادی فایل می‌یابیم؛ از جمله هشت فایل BAM که در نسخهٔ پیشین این گردش‌کار برای نشان‌دادن هم‌ترازسازی و شمارش به‌کار رفته بودند. تمرکز ما بر دو پوشه‌ای است که در مسیر `quants` قرار دارند و خروجی _Salmon_ بر روی دو فایل را در خود دارند.

```
list.files(dir)
```

```
##  [1] "GSE52778_series_matrix.txt"        "Homo_sapiens.GRCh37.75_subset.gtf"
##  [3] "SRR1039508_subset.bam"             "SRR1039509_subset.bam"            
##  [5] "SRR1039512_subset.bam"             "SRR1039513_subset.bam"            
##  [7] "SRR1039516_subset.bam"             "SRR1039517_subset.bam"            
##  [9] "SRR1039520_subset.bam"             "SRR1039521_subset.bam"            
## [11] "SraRunInfo_SRP033351.csv"          "quants"                           
## [13] "sample_table.csv"
```

```
list.files(file.path(dir, "quants"))
```

```
## [1] "SRR1039508" "SRR1039509"
```

به‌طور معمول، جدولی شامل اطلاعات تفصیلی برای هر یک از نمونه‌ها داریم که آن‌ها را به فایل‌های FASTQ و پوشه‌های مربوط به _Salmon_ متصل می‌کند. برای پروژهٔ خود می‌توانید چنین فایلی با قالب مقادیر جداشده با کاما (CSV) را با یک ویرایشگر متن یا نرم‌افزار صفحه‌گسترده مانند Excel بسازید.

چنین فایل CSV‌ای را با _read.csv_ بارگذاری می‌کنیم:

```
csvfile <- file.path(dir, "sample_table.csv")
coldata <- read.csv(csvfile, row.names=1, stringsAsFactors=FALSE)
coldata
```

```
##            SampleName    cell   dex albut        Run avgLength Experiment
## SRR1039508 GSM1275862  N61311 untrt untrt SRR1039508       126  SRX384345
## SRR1039509 GSM1275863  N61311   trt untrt SRR1039509       126  SRX384346
## SRR1039512 GSM1275866 N052611 untrt untrt SRR1039512       126  SRX384349
## SRR1039513 GSM1275867 N052611   trt untrt SRR1039513        87  SRX384350
## SRR1039516 GSM1275870 N080611 untrt untrt SRR1039516       120  SRX384353
## SRR1039517 GSM1275871 N080611   trt untrt SRR1039517       126  SRX384354
## SRR1039520 GSM1275874 N061011 untrt untrt SRR1039520       101  SRX384357
## SRR1039521 GSM1275875 N061011   trt untrt SRR1039521        98  SRX384358
##               Sample    BioSample
## SRR1039508 SRS508568 SAMN02422669
## SRR1039509 SRS508567 SAMN02422675
## SRR1039512 SRS508571 SAMN02422678
## SRR1039513 SRS508572 SAMN02422670
## SRR1039516 SRS508575 SAMN02422682
## SRR1039517 SRS508576 SAMN02422673
## SRR1039520 SRS508579 SAMN02422683
## SRR1039521 SRS508580 SAMN02422677
```

برای نشان‌دادنِ واردسازی داده‌های کمی‌سازیِ _Salmon_ به R، تنها با دو نمونه‌ای کار می‌کنیم که در بستهٔ _airway_ ارائه شده‌اند. یک ستون به نام `names` و ستونی دیگر به نام `files` می‌سازیم:

```
coldata <- coldata[1:2,]
coldata$names <- coldata$Run
coldata$files <- file.path(dir, "quants", coldata$names, "quant.sf.gz")
file.exists(coldata$files)
```

```
## [1] TRUE TRUE
```

اکنون بستهٔ _tximeta_ را بارگذاری و تابع اصلی آن را اجرا می‌کنیم:

```
library("tximeta")
se <- tximeta(coldata)
```

```
## importing salmon quantification files
```

```
## reading in files with read_tsv
```

```
## 1 2 
## found matching transcriptome:
## [ GENCODE - Homo sapiens - release 29 ]
## useHub=TRUE: checking for TxDb via 'AnnotationHub'
## found matching TxDb via 'AnnotationHub'
## loading from cache
## Loading required package: GenomicFeatures
## Loading required package: AnnotationDbi
## generating transcript ranges
```

اگر _tximeta_ کدِ کنترلی (checksum) ترنسکریپتومِ مرجع را تشخیص داده باشد (جزئیات در وینگت _[tximeta](https://bioconductor.org/packages/3.23/tximeta)_) و اتصال اینترنتی فعال داشته باشیم، _tximeta_ داده‌های حاشیه‌نویسی مرتبط را از منابع مختلف یافته و بارگیری خواهد کرد. چند نکته: داده‌های حاشیه‌نویسی فقط یک‌بار بارگیری و تجزیه می‌شوند و از آن پس، در صورت نیاز، نسخه‌های ذخیره‌شده در نهانگاه محلیِ فرا‌داده استفاده خواهد شد (اگر برای بار دوم داده‌ای را بارگذاری کنید که در برابر همان transcript (رونوشت)‌های مرجع کمی‌سازی شده است). همچنین، در اولین اجرا، _tximeta_ از شما می‌خواهد محل پیش‌فرض نهانگاه را تأیید کنید (مطابق الگوی مکان نهانگاه که در سایر بسته‌های R و Bioconductor نیز به‌کار می‌رود). این مکان را می‌توانید هر زمان بعداً تغییر دهید.

در بخش بعدی دربارهٔ ساختار شیء `se` بحث خواهیم کرد، اما فعلاً صرفاً به ابعاد آن نگاه می‌کنیم. توجه داشته باشید که _tximeta_ داده را در سطح رونوشت وارد می‌کند.

```
dim(se)
```

```
## [1] 205870      2
```

```
head(rownames(se))
```

```
## [1] "ENST00000456328.2" "ENST00000450305.2" "ENST00000488147.1"
## [4] "ENST00000619216.1" "ENST00000473358.1" "ENST00000469289.1"
```

از آنجا که این گردش‌کار بر تحلیل در سطح ژن متمرکز است، اکنون کمی‌سازی‌های سطح رونوشت را به سطح ژن خلاصه می‌کنیم (که درونی از روش‌های موجود در _tximport_ (Soneson, Love, and Robinson 2015) بهره می‌گیرد). نگاشت صحیحِ رونوشت‌به-ژن به‌طور خودکار بر پایهٔ فرا‌دادهٔ ذخیره‌شده درون شیء `se` ساخته می‌شود.

```
gse <- summarizeToGene(se)
```

```
## loading existing TxDb created: 2026-06-02 17:09:55
```

```
## obtaining transcript-to-gene mapping from database
```

```
## generating gene ranges
```

```
## assignRanges='range': gene ranges assigned by total range of isoforms
##   see details at: ?summarizeToGene,SummarizedExperiment-method
```

```
## summarizing abundance
```

```
## summarizing counts
```

```
## summarizing length
```

اکنون می‌توانیم بررسی کنیم که ابعاد کاهش یافته و شناسه‌های سطرها اکنون شناسه‌های ژن هستند:

```
dim(gse)
```

```
## [1] 58294     2
```

```
head(rownames(gse))
```

```
## [1] "ENSG00000000003.14" "ENSG00000000005.5"  "ENSG00000000419.12"
## [4] "ENSG00000000457.13" "ENSG00000000460.16" "ENSG00000000938.12"
```

## ۲٫۴ توابع واردسازی _DESeq2_

هرچند بخش بالا به کاربرد _Salmon_ و _tximeta_ اختصاص داشت، ورودی‌های ممکن متعددی برای _DESeq2_ وجود دارد که هر یک توابع واردسازیِ ویژهٔ خود را دارند.
ابزارهای زیر می‌توانند داده‌های شمارش را برای استفاده در _DESeq2_ تولید یا تجمیع کنند: _tximport_ (Soneson, Love, and Robinson 2015)، _tximeta_ (Love et al. 2020)، _htseq-count_ (Anders, Pyl, and Huber 2015)، _featureCounts_ (Liao, Smyth, and Shi 2014)، _summarizeOverlaps_ (Lawrence et al. 2013).

|تابع |بسته |چارچوب |خروجی |تابع ورودی برای _DESeq2_ |
| --- | --- | --- | --- | --- |
|_tximport_ |_[tximport](https://bioconductor.org/packages/3.23/tximport)_ |R/Bioconductor |فهرستی از ماتریس‌ها |_DESeqDataSetFromTximport_ |
|_tximeta_ |_[tximeta](https://bioconductor.org/packages/3.23/tximeta)_ |R/Bioconductor |_SummarizedExperiment_ |_DESeqDataSet_ |
|_htseq-count_ |[HTSeq](http://www-huber.embl.de/users/anders/HTSeq) |Python |فایل‌ها |_DESeqDataSetFromHTSeq_ |
|_featureCounts_ |_[Rsubread](https://bioconductor.org/packages/3.23/Rsubread)_ |R/Bioconductor |ماتریس |_DESeqDataSetFromMatrix_ |
|_summarizeOverlaps_ |_[GenomicAlignments](https://bioconductor.org/packages/3.23/GenomicAlignments)_ |R/Bioconductor |_SummarizedExperiment_ |_DESeqDataSet_ |

در ادامه، کلاس شیئی را که _tximeta_ می‌سازد و در بالا به‌صورت `se` و `gse` ذخیره شد توصیف می‌کنیم، و این‌که چگونه از آن برای استفاده در _DESeq2_ یک شیء _DESeqDataSet_ بسازیم (سایر توابعِ بالا نیز یک _DESeqDataSet_ ایجاد می‌کنند).

## ۲٫۵ شیء _SummarizedExperiment_

**اجزای سازندهٔ یک شیء _SummarizedExperiment_.** `assay` (بلوک صورتی) شامل ماتریس شمارش است، `rowRanges` (بلوک آبی) اطلاعات مربوط به بازه‌های ژنومی را دربر می‌گیرد و `colData` (بلوک سبز) اطلاعات مربوط به نمونه‌ها را شامل می‌شود. خط هایلایت‌شده در هر بلوک نشان‌دهندهٔ سطر نخست است (توجه کنید که سطر نخستِ `colData` با ستون نخستِ `assay` هم‌تراز است).

محفظهٔ _SummarizedExperiment_ در شکل بالا ترسیم شده و در تازه‌ترین مقالهٔ Bioconductor (Huber et al. 2015) بحث شده است. در مورد ما، _tximeta_ شیئی به نام `gse` با سه ماتریس ساخته است: «counts» — شمارش‌های برآوردیِ قطعه‌ها برای هر ژن و هر نمونه؛ «abundance» — abundance (فراوانی) برآوردیِ رونوشت‌ها برحسب TPM؛ و «length» — طول‌های مؤثر ژن که تغییرات طول ناشی از سوگیری‌ها و نیز ناشی از الگوی استفاده از رونوشت‌ها را دربر می‌گیرند. نام آزمون‌ها را می‌توان با _assayNames_ مشاهده کرد و خودِ آزمون‌ها به‌صورت `assays` (فهرستی از ماتریس‌ها) نگهداری می‌شوند. نخستین ماتریسِ این فهرست را می‌توان با `assay` بیرون کشید. `rowRanges` برای شیء ما _GRanges_ ژن‌هاست (از چپ‌ترین موقعیتِ همهٔ رونوشت‌ها تا راست‌ترین موقعیتِ آن‌ها).
اجزای سازنده‌ی _SummarizedExperiment_ با تابع هم‌نام در R در دسترس‌اند: `assay` (یا `assays`)، `rowRanges` و `colData`.

اکنون ماتریس کامل count (شمارش) متناظر با همهٔ نمونه‌ها و همهٔ داده‌ها را که در بستهٔ _airway_ فراهم شده است بارگذاری می‌کنیم و تحلیل را با شیء کامل داده ادامه می‌دهیم. توجه کنید که اطلاعات مربوط به اهداکنندهٔ ردهٔ سلولی و تیمار با دگزامتازون اکنون ستون‌های `donor` و `condition` از فرادادهٔ ستون‌ها هستند.

می‌توانیم این شیء _SummarizedExperiment_ را با نگاه کردن به ماتریس‌ها در شکاف `assays`، داده‌های فنوتیپی دربارهٔ نمونه‌ها در شکاف `colData`، و داده‌های مربوط به gene (ژن)‌ها در شکاف `rowRanges` بررسی کنیم.

```
data(gse)
gse
```

```
## class: RangedSummarizedExperiment 
## dim: 58294 8 
## metadata(6): tximetaInfo quantInfo ... txomeInfo txdbInfo
## assays(3): counts abundance length
## rownames(58294): ENSG00000000003.14 ENSG00000000005.5 ...
##   ENSG00000285993.1 ENSG00000285994.1
## rowData names(1): gene_id
## colnames(8): SRR1039508 SRR1039509 ... SRR1039520 SRR1039521
## colData names(3): names donor condition
```

شمارش‌ها نخستین ماتریس هستند، پس می‌توانیم آن‌ها را تنها با `assay` بررسی کنیم:

```
assayNames(gse)
```

```
## [1] "counts"    "abundance" "length"
```

```
head(assay(gse), 3)
```

```
##                    SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516
## ENSG00000000003.14    708.164    467.962    900.992    424.368   1188.295
## ENSG00000000005.5       0.000      0.000      0.000      0.000      0.000
## ENSG00000000419.12    455.000    510.000    604.000    352.000    583.000
##                    SRR1039517 SRR1039520 SRR1039521
## ENSG00000000003.14   1090.668    805.929    599.337
## ENSG00000000005.5       0.000      0.000      0.000
## ENSG00000000419.12    773.999    409.999    499.000
```

```
colSums(assay(gse))
```

```
## SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516 SRR1039517 SRR1039520 
##   21100805   19298584   26145537   15688246   25268618   31891456   19683767 
## SRR1039521 
##   21813903
```

هنگام چاپ `rowRanges`، بازه‌ها برای پنج ژن نخست و پنج ژن آخر نشان داده می‌شوند:

```
rowRanges(gse)
```

```
## GRanges object with 58294 ranges and 1 metadata column:
##                      seqnames              ranges strand |            gene_id
##                         <Rle>           <IRanges>  <Rle> |        <character>
##   ENSG00000000003.14     chrX 100627109-100639991      - | ENSG00000000003.14
##    ENSG00000000005.5     chrX 100584802-100599885      + |  ENSG00000000005.5
##   ENSG00000000419.12    chr20   50934867-50958555      - | ENSG00000000419.12
##   ENSG00000000457.13     chr1 169849631-169894267      - | ENSG00000000457.13
##   ENSG00000000460.16     chr1 169662007-169854080      + | ENSG00000000460.16
##                  ...      ...                 ...    ... .                ...
##    ENSG00000285990.1    chr14   19244904-19269380      - |  ENSG00000285990.1
##    ENSG00000285991.1     chr6 149817937-149896011      - |  ENSG00000285991.1
##    ENSG00000285992.1     chr8   47129262-47132628      + |  ENSG00000285992.1
##    ENSG00000285993.1    chr18   46409197-46410645      - |  ENSG00000285993.1
##    ENSG00000285994.1    chr10   12563151-12567351      + |  ENSG00000285994.1
##   -------
##   seqinfo: 25 sequences (1 circular) from hg38 genome
```

همچنین `rowRanges` در شکاف `seqinfo` فراداده‌ای دربارهٔ توالی‌ها (در این‌جا کروموزوم‌ها) دارد:

```
seqinfo(rowRanges(gse))
```

```
## Seqinfo object with 25 sequences (1 circular) from hg38 genome:
##   seqnames seqlengths isCircular genome
##   chr1      248956422      FALSE   hg38
##   chr2      242193529      FALSE   hg38
##   chr3      198295559      FALSE   hg38
##   chr4      190214555      FALSE   hg38
##   chr5      181538259      FALSE   hg38
##   ...             ...        ...    ...
##   chr21      46709983      FALSE   hg38
##   chr22      50818468      FALSE   hg38
##   chrX      156040895      FALSE   hg38
##   chrY       57227415      FALSE   hg38
##   chrM          16569       TRUE   hg38
```

`colData` برای _SummarizedExperiment_ بازتاب‌دهندهٔ _data.frame_ای است که به تابع `tximeta` برای وارد کردن داده‌های کمی‌سازی داده شده بود. در این‌جا می‌بینیم که ستون‌هایی برای نام نمونه‌ها، همچنین شناسهٔ اهداکننده و وضعیت تیمار (تیمار با دگزامتازون یا بدون تیمار) وجود دارد.

```
colData(gse)
```

```
## DataFrame with 8 rows and 3 columns
##                 names    donor     condition
##              <factor> <factor>      <factor>
## SRR1039508 SRR1039508  N61311  Untreated    
## SRR1039509 SRR1039509  N61311  Dexamethasone
## SRR1039512 SRR1039512  N052611 Untreated    
## SRR1039513 SRR1039513  N052611 Dexamethasone
## SRR1039516 SRR1039516  N080611 Untreated    
## SRR1039517 SRR1039517  N080611 Dexamethasone
## SRR1039520 SRR1039520  N061011 Untreated    
## SRR1039521 SRR1039521  N061011 Dexamethasone
```

## ۲٫۶ نقطهٔ انشعاب

در این مرحله، قطعه‌هایی را که با ژن‌ها در مدل ژنی مشخص‌شده هم‌پوشانی داشتند شمرده‌ایم. این یک نقطهٔ انشعاب است که در آن می‌توان از انواع بسته‌های Bioconductor برای کاوش و differential expression analysis (تحلیل بیان تفاضلی) داده‌های شمارش استفاده کرد، از جمله _[edgeR](https://bioconductor.org/packages/3.23/edgeR)_ (Robinson, McCarthy, and Smyth 2009)، _[limma](https://bioconductor.org/packages/3.23/limma)_ با روش voom (Law et al. 2014)، _[DSS](https://bioconductor.org/packages/3.23/DSS)_ (Wu, Wang, and Wu 2013)، _[EBSeq](https://bioconductor.org/packages/3.23/EBSeq)_ (Leng et al. 2013) و _[baySeq](https://bioconductor.org/packages/3.23/baySeq)_ (Hardcastle and Kelly 2010). Schurch و همکاران (2016) [عملکرد](https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/27022035/) روش‌های آماری مختلف برای RNA-seq را با تعداد زیادی تکرار زیستی مقایسه کردند و می‌تواند به کاربران کمک کند تصمیم بگیرند کدام ابزارها معقول است استفاده شوند و برای دستیابی به حساسیت معینی به چند تکرار زیستی نیاز است. ما با _[DESeq2](https://bioconductor.org/packages/3.23/DESeq2)_ (Love, Huber, and Anders 2014) ادامه خواهیم داد. شیء _SummarizedExperiment_ تمام چیزی است که برای شروع تحلیل نیاز داریم. در بخش بعدی نشان می‌دهیم چگونه با استفاده از آن شیء دادهٔ مورد استفادهٔ _[DESeq2](https://bioconductor.org/packages/3.23/DESeq2)_ را بسازیم.

# 3 شیء _DESeqDataSet_، اطلاعات نمونه و فرمول طراحی

بسته‌های نرم‌افزاری Bioconductor اغلب یک کلاس سفارشی برای نگه‌داری داده‌ها تعریف و استفاده می‌کنند تا مطمئن شوند همهٔ شکاف‌های داده‌ای لازم به‌طور یکنواخت فراهم شده و شرایط را برآورده می‌کنند. افزون بر این، Bioconductor کلاس‌های داده‌ای عمومی (مانند _SummarizedExperiment_) دارد که می‌توان از آن‌ها برای جابه‌جایی داده‌ها بین بسته‌ها استفاده کرد. همچنین کلاس‌های هسته‌ای Bioconductor قابلیت‌های مفیدی فراهم می‌کنند: برای نمونه، زیرمجموعه‌گیری یا بازچینی سطرها یا ستون‌های یک _SummarizedExperiment_ به‌طور خودکار _rowRanges_ و _colData_ متناظر را نیز زیرمجموعه‌گیری یا بازچینی می‌کند، که می‌تواند از جابه‌جایی تصادفی نمونه‌ها که در غیر این صورت به نتایج گمراه‌کننده منجر می‌شد جلوگیری کند. با _SummarizedExperiment_ همهٔ این‌ها در پس‌زمینه رسیدگی می‌شود.

در _DESeq2_، کلاس سفارشی _DESeqDataSet_ نام دارد. این کلاس بر پایهٔ _SummarizedExperiment_ ساخته شده است و تبدیل اشیای _SummarizedExperiment_ به _DESeqDataSet_ آسان است، که در ادامه نشان می‌دهیم. یکی از دو تفاوت اصلی این است که شکاف `assay` به‌جای خود با استفاده از تابع دسترسی _counts_ در دسترس است و کلاس _DESeqDataSet_ اعمال می‌کند که مقادیر این ماتریس اعداد صحیح نامنفی باشند.

تفاوت دوم این است که _DESeqDataSet_ یک «فرمول طراحی» همراه دارد. طرح آزمایشی در ابتدای تحلیل تعیین می‌شود، زیرا به بسیاری از توابع _DESeq2_ اطلاع می‌دهد که با نمونه‌ها در تحلیل چگونه رفتار کنند (یک استثناء، برآورد عامل اندازه است؛ یعنی تعدیل برای اندازه‌های متفاوت کتابخانه‌ها که به فرمول طراحی وابسته نیست). فرمول طراحی مشخص می‌کند کدام ستون‌ها در جدول اطلاعات نمونه (`colData`) طرح آزمایشی را تعیین می‌کنند و این عوامل چگونه باید در تحلیل به کار روند.

ابتدا، بیایید ستون‌های `colData` از `gse` را بررسی کنیم. می‌توان هر یک از ستون‌ها را تنها با استفاده از `$` مستقیماً روی _SummarizedExperiment_ یا _DESeqDataSet_ مشاهده کرد.

```
gse$donor
```

```
## [1] N61311  N61311  N052611 N052611 N080611 N080611 N061011 N061011
## Levels: N052611 N061011 N080611 N61311
```

```
gse$condition
```

```
## [1] Untreated     Dexamethasone Untreated     Dexamethasone Untreated    
## [6] Dexamethasone Untreated     Dexamethasone
## Levels: Untreated Dexamethasone
```

در صورت تمایل می‌توانیم نام متغیرهای خود را عوض کنیم. بیایید از `cell` برای نشان دادن ردهٔ سلولی اهداکننده و از `dex` برای نشان دادن وضعیت تیمار استفاده کنیم.

```
gse$cell <- gse$donor
gse$dex <- gse$condition
```

همچنین می‌توانیم نام سطوح را تغییر دهیم. هنگام تغییر نام سطوح، حیاتی است که ترتیب را تغییر ندهیم. در این‌جا `"Untreated"` را به `"untrt"` و `"Dexamethasone"` را به `"trt"` تغییر نام می‌دهیم:

```
levels(gse$dex)
```

```
## [1] "Untreated"     "Dexamethasone"
```

```
# when renaming levels, the order must be preserved!
levels(gse$dex) <- c("untrt", "trt")
```

ساده‌ترین فرمول طراحی برای differential expression analysis (تحلیل بیان تفاضلی) `~ condition` است، که در آن `condition` ستونی در `colData(dds)` است که مشخص می‌کند نمونه‌ها به کدام‌یک از دو (یا چند) گروه تعلق دارند. برای آزمایش airway، ما `~ cell + dex` را مشخص می‌کنیم؛ به این معنا که می‌خواهیم اثر دگزامتازون (`dex`) را در حالی بیازماییم که برای اثر رده‌های سلولی متفاوت (`cell`) کنترل می‌کنیم.

توجه: در R ترجیح داده می‌شود سطح نخست یک عامل، سطح مرجع باشد (برای مثال، کنترل یا نمونه‌های بدون تیمار). در این مورد، هنگامی که جدول `colData` ساخته شد، نمونه‌های بدون تیمار از پیش به‌عنوان مرجع تنظیم شده بودند، اما اگر این‌گونه نبود می‌توانستیم همان‌طور که در پایین نشان داده شده از _relevel_ استفاده کنیم. در حالی که `levels(...) <-` در بالا صرفاً برای تغییر نام رشته‌های کاراکتری متناظر با سطوح بود، _relevel_ تابعی کاملاً متفاوت است که تعیین می‌کند متغیرها چگونه کُدگذاری شوند و contrast (مقایسه)ها چگونه محاسبه شوند. برای یک مقایسهٔ دو-گروهی، استفاده از _relevel_ برای تغییر سطح مرجع، علامت ضریب متناظر با یک مقایسه بین دو گروه را معکوس می‌کند.

```
library("magrittr")
gse$dex %<>% relevel("untrt")
gse$dex
```

```
## [1] untrt trt   untrt trt   untrt trt   untrt trt  
## Levels: untrt trt
```

`%<>%` عملگر پایپیِ تخصیص مرکب از بستهٔ _[magrittr](https://cran.r-project.org/package=magrittr)_ است، خط کد بالا یک
شیوهٔ بیان موجز:

```
gse$dex <- relevel(gse$dex, "untrt")
```

برای اجرای مدل‌های _DESeq2_ می‌توانید از نگارش فرمول در R برای بیان هر طرح آزمایشی با اثرات ثابت استفاده کنید. توجه داشته باشید که _DESeq2_ همان نگارش فرمولِ تابع _lm_ در R پایه را به‌کار می‌گیرد. اگر هدف پژوهش این است که تعیین کنیم برای کدام genes (ژن‌ها) اثرِ تیمار در میان گروه‌ها متفاوت است، می‌توان عبارت‌های برهم‌کنشی را در طرح وارد و با طرحی مانند `~ group + treatment + group:treatment` آزمون کرد. برای نمونه‌های بیشتر به صفحهٔ راهنمای `?results` مراجعه کنید. در ادامه نشان می‌دهیم که چگونه می‌توان از یک عبارت برهم‌کنشی برای آزمون تغییرات وابسته به شرط در طول زمان، در یک مثال دورهٔ زمانی، استفاده کرد.

در بخش‌های بعدی، ساخت یک _DESeqDataSet_ را از دو نقطهٔ شروع نشان می‌دهیم:

* از یک شیء _SummarizedExperiment_
* از یک ماتریس count (شمارش) و یک جدول اطلاعات نمونه

برای یک مثال کامل از استفاده از بستهٔ پایتونی _HTSeq_ برای شمارش read (خوانش)، به وینیتِ _[pasilla](https://bioconductor.org/packages/3.23/pasilla)_ مراجعه کنید. برای مثالی از ساخت _DESeqDataSet_ از فایل‌هایی که به‌وسیلهٔ _htseq-count_ تولید شده‌اند، به وینیتِ _[DESeq2](https://bioconductor.org/packages/3.23/DESeq2)_ مراجعه کنید.

## ۳٫۱ شروع از _SummarizedExperiment_

دوباره می‌توانیم به‌سرعت میلیون‌ها قطعه‌ای را که _Salmon_ می‌تواند به ژن‌ها نگاشت کند بررسی کنیم (آرگومان دوم تابع _round_ تعداد رقم‌های اعشاری را مشخص می‌کند).

```
round( colSums(assay(gse)) / 1e6, 1 )
```

```
## SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516 SRR1039517 SRR1039520 
##       21.1       19.3       26.1       15.7       25.3       31.9       19.7 
## SRR1039521 
##       21.8
```

وقتی شیء _SummarizedExperiment_ را به‌طور کامل حاشیه‌نویسی کردیم، می‌توانیم یک شیء _DESeqDataSet_ از آن بسازیم که نقطهٔ آغاز تحلیل خواهد بود.
در این مرحله یک طرح مناسب برای تحلیل اضافه می‌کنیم:

```
library("DESeq2")
```

```
dds <- DESeqDataSet(gse, design = ~ cell + dex)
```

## ۳٫۲ شروع از ماتریس‌های شمارش

در این بخش نشان می‌دهیم که چگونه یک _DESeqDataSet_ را در حالتی می‌سازیم که فقط یک ماتریس شمارش و یک جدول اطلاعات نمونه در اختیار داریم.

توجه: اگر یک _SummarizedExperiment_ آماده کرده‌اید باید از این بخش صرف‌نظر کنید. در حالی‌که در بخش پیشین، _DESeqDataSet_ را از یک _SummarizedExperiment_ می‌ساختیم، اینجا صرفاً برای نمایش، اجزای منفرد (ماتریس شمارش و اطلاعات نمونه) را از _SummarizedExperiment_ استخراج می‌کنیم تا دوباره یک شیء جدید بسازیم. در عمل، ماتریس شمارش معمولاً از یک فایل خوانده می‌شود یا شاید با تابعی در R مانند _featureCounts_ از بستهٔ _[Rsubread](https://bioconductor.org/packages/3.23/Rsubread)_ (Liao, Smyth, and Shi 2014) تولید شود.

اطلاعات در یک شیء _SummarizedExperiment_ با توابع دسترسی قابل بازیابی است. برای نمونه، برای دیدن داده‌های واقعی، یعنی در اینجا شمارش قطعه‌ها، از تابع _assay_ استفاده می‌کنیم. (تابع _head_ خروجی را به چند خط اول محدود می‌کند.)

```
countdata <- round(assays(gse)[["counts"]])
head(countdata, 3)
```

```
##                    SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516
## ENSG00000000003.14        708        468        901        424       1188
## ENSG00000000005.5           0          0          0          0          0
## ENSG00000000419.12        455        510        604        352        583
##                    SRR1039517 SRR1039520 SRR1039521
## ENSG00000000003.14       1091        806        599
## ENSG00000000005.5           0          0          0
## ENSG00000000419.12        774        410        499
```

در این ماتریس شمارش، هر سطر نمایندهٔ یک ژن، هر ستون نمایندهٔ یک کتابخانهٔ RNA توالی‌یابی‌شده است، و مقادیر، شمارش‌های برآوردشدهٔ قطعه‌هایی را می‌دهند که به‌صورت احتمالی در هر کتابخانه به ژن متناظر توسط _Salmon_ انتساب یافته‌اند. همچنین دربارهٔ هر یک از نمونه‌ها (ستون‌های ماتریس شمارش) اطلاعاتی داریم. اگر داده‌های شمارش را به روش دیگری وارد کرده‌اید، مثلاً با بارگذاری یک ماتریس شمارش ازپیش‌محاسبه‌شده، بسیار مهم است که به‌صورت دستی بررسی کنید ستون‌های ماتریس شمارش با ردیف‌های جدول اطلاعات نمونه متناظر باشند.

```
coldata <- colData(gse)
```

اکنون همهٔ اجزای لازم برای آماده‌سازی شیء داده‌ها در قالبی مناسب برای تحلیل را در اختیار داریم، یعنی:

* `countdata` : جدولی شامل شمارش‌های قطعه‌ها
* `coldata` : جدولی شامل اطلاعات مربوط به نمونه‌ها

برای ساختن شیء _DESeqDataSet_ از ماتریس شمارش‌ها و جدول اطلاعات نمونه، از این دستور استفاده می‌کنیم:

```
ddsMat <- DESeqDataSetFromMatrix(countData = countdata,
                                 colData = coldata,
                                 design = ~ cell + dex)
```

در ادامه با شیئی کار خواهیم کرد که در بخش _SummarizedExperiment_ ساخته شد.

# 4 تحلیل اکتشافی و بصری‌سازی

در این جریان کار دو مسیر جداگانه وجود دارد؛ مسیری که ابتدا می‌بینیم شامل دگرگونیِ شمارش‌ها برای کاوش بصریِ روابط میان نمونه‌هاست. در بخش دوم، برای آزمون‌های آماری به شمارش‌های خام اصلی برمی‌گردیم. این موضوع حیاتی است، زیرا روش‌های آزمون آماری برای محاسبهٔ دقت اندازه‌گیری‌ها به داده‌های شمارش اصلی (نه مقیاس‌بندی‌شده یا دگرگون‌شده) تکیه می‌کنند.

## ۴٫۱ پیش‌فیلتر کردن مجموعه‌داده

ماتریس شمارش ما در _DESeqDataSet_ شامل سطرهای زیادی با فقط صفر، و افزون بر آن، سطرهای زیادی با صرفاً چند قطعه در مجموع است. برای کاهش اندازهٔ شیء و افزایش سرعت اجرای توابع، می‌توانیم سطرهایی را که فاقد اطلاعات یا تقریباً بی‌اطلاعات دربارهٔ میزان بیان ژن هستند حذف کنیم. در اینجا پیش‌پالایش انجام می‌دهیم تا فقط سطرهایی را نگه داریم که حداقل برای تعدادِ مینیممی از نمونه‌ها، شمارشی دست‌کم ۱۰ دارند. آستانهٔ ۱۰ انتخابی معقول برای RNA-seq توده‌ای است. برای حداقل تعداد نمونه‌ها پیشنهاد می‌شود کوچک‌ترین اندازهٔ گروه مشخص شود؛ برای مثال اینجا در هر گروه ۴ نمونه وجود دارد. اگر گروه‌های گسسته وجود نداشته باشد، می‌توان حداقل تعداد نمونه‌هایی را به‌کار برد که در آن‌ها شمارش‌های ناصفر جالب توجه تلقی می‌شوند. وزن‌دهی/فیلترکردنِ افزوده برای بهبود توان، در گام‌های بعدی جریان کار اعمال خواهد شد.

```
nrow(dds)
```

```
## [1] 58294
```

```
smallestGroupSize <- 4
keep <- rowSums(counts(dds) >= 10) >= smallestGroupSize
dds <- dds[keep,]
nrow(dds)
```

```
## [1] 16637
```

## ۴٫۲ تبدیل تثبیت‌کنندهٔ واریانس و تبدیل rlog

بسیاری از روش‌های آماری متداول برای تحلیل اکتشافیِ داده‌های چندبعدی، مانند خوشه‌بندی و تحلیل مؤلفه‌های اصلی (PCA)، زمانی بهترین کارکرد را دارند که دامنهٔ واریانس در گستره‌های مختلفِ میانگین، به‌طور کلی مشابه باشد. هنگامی که مقدار مورد انتظارِ واریانس تقریباً در میانگین‌های مختلف یکسان است، می‌گوییم داده‌ها _هم‌واریانس_ هستند. بااین‌حال برای شمارش‌های RNA-seq، واریانس مورد انتظار با افزایش میانگین رشد می‌کند. برای نمونه، اگر PCA مستقیماً روی یک ماتریسِ شمارش یا شمارش‌های برآمده از normalization (نرمال‌سازی) انجام شود (مثلاً برای تصحیح تفاوت‌های عمق توالی‌یابی)، نمودار حاصل معمولاً عمدتاً به ژن‌هایی وابسته است که بالاترین شمارش‌ها را دارند، زیرا این ژن‌ها بزرگ‌ترین تفاوت‌های مطلق را میان نمونه‌ها نشان می‌دهند. راهبردی ساده و پرتکرار برای پرهیز از این وضعیت، گرفتن لگاریتمِ مقادیرِ شمارشِ نرمال‌سازی‌شده به‌علاوهٔ یک شبه‌شمارشِ ۱ است؛ بااین‌حال، بسته به انتخاب شبه‌شمارش، این‌بار ژن‌هایی با بسیار کمترین شمارش، سهم زیادی از نویز را به نمودار حاصل می‌افزایند، زیرا گرفتن لگاریتم از شمارش‌های کوچک، واریانس‌شان را به‌طور کاذب افزایش می‌دهد. می‌توانیم این ویژگیِ شمارش‌ها را به‌سرعت با داده‌های شبیه‌سازی‌شده نشان دهیم (در اینجا، شمارش‌های پواسون با دامنه‌ای از پارامتر لاندا از 0.1 تا 100). انحراف معیار هر سطر (ژن‌ها) را در برابر میانگین ترسیم می‌کنیم:

```
lambda <- 10^seq(from = -1, to = 2, length = 1000)
cts <- matrix(rpois(1000*100, lambda), ncol = 100)
library("vsn")
meanSdPlot(cts, ranks = FALSE)
```

و برای شمارش‌های لگاریتم‌دگرگون‌شده:

```
log.cts.one <- log2(cts + 1)
meanSdPlot(log.cts.one, ranks = FALSE)
```

لگاریتم با یک شبه‌شمارش کوچک، تفاوت‌ها را زمانی تقویت می‌کند که ...
مقادیر نزدیک به صفر هستند. ژن‌های با count (شمارش) پایین و نسبت سیگنال به نویز کم، به‌شکل نامتناسبی بر فاصله‌های نمونه-به-نمونه و نمودارهای PCA اثر می‌گذارند.

به‌عنوان راه‌حل، _DESeq2_ دو تبدیل برای داده‌های شمارش ارائه می‌کند که واریانس را در سراسر میانگین پایدار می‌کنند:
_variance stabilizing transformation_ یا VST برای داده‌های دوجمله‌ای منفی با روند dispersion (پراکندگی)-میانگین (Anders and Huber 2010) که در تابع _vst_ پیاده‌سازی شده است،
و _regularized-logarithm transformation_ یا _rlog_ (Love, Huber, and Anders 2014).

برای ژن‌های با شمارش‌های بالا، هر دو تبدیل VST و rlog نتیجه‌ای مشابه با تبدیل لگاریتمی معمولِ پایهٔ 2 روی شمارش‌های نرمال‌شدهٔ حاصل از normalization (نرمال‌سازی) می‌دهند. اما برای ژن‌های با شمارش‌های پایین‌تر، مقادیر به‌سمت یک مقدار میانی جمع می‌شوند. داده‌های تبدیل‌شده با VST یا rlog به‌تقریب هم‌واریانس می‌شوند (روند تخت‌تر در _meanSdPlot_) و بنابراین می‌توان آن‌ها را مستقیماً برای محاسبهٔ فاصله‌ها بین نمونه‌ها، ساخت نمودارهای PCA، یا به‌عنوان ورودیِ روش‌های پایین‌دستی که با داده‌های هم‌واریانس بهترین کارکرد را دارند، به‌کار برد.

Which transformation to choose? انتخاب کدام تبدیل مناسب‌تر است؟ VST بسیار سریع‌تر محاسبه می‌شود و نسبت به پرت‌های دارای شمارش بالا حساسیت کمتری از rlog دارد. rlog معمولاً روی مجموعه‌داده‌های کوچک (n < 30) خوب عمل می‌کند و وقتی دامنهٔ عمق توالی‌گزینی بین نمونه‌ها بسیار گسترده باشد (اختلافی در حد یک مرتبهٔ بزرگی)، احتمال دارد از VST بهتر عمل کند. ازاین‌رو VST را برای مجموعه‌داده‌های متوسط تا بزرگ (n > 30) توصیه می‌کنیم. می‌توانید هر دو تبدیل را انجام دهید و `meanSdPlot` یا نمودارهای PCA تولیدشده را مطابق توضیحات زیر مقایسه کنید.

توجه کنید که دو تبدیل ارائه‌شده توسط DESeq2 برای کاربردهایی غیر از differential expression analysis (تحلیل بیان تفاضلی) در نظر گرفته شده‌اند. برای این تحلیل توصیه می‌کنیم از تابع _DESeq_ روی شمارش‌های خام استفاده کنید، همان‌گونه که بعدتر در این جریان کار توضیح داده می‌شود؛ این روش در گام برآورد پراکندگی نیز وابستگی واریانسِ شمارش‌ها به مقدار میانگین را در نظر می‌گیرد.

هر دو تابع _vst_ و _rlog_ یک شیء از کلاس _DESeqTransform_ برمی‌گردانند که بر پایهٔ کلاس _SummarizedExperiment_ است. مقادیر تبدیل‌شده دیگر «شمارش» نیستند و در شکاف _assay_ ذخیره می‌شوند. _colData_ای که به `dds` پیوست شده بود همچنان در دسترس است:

```
vsd <- vst(dds, blind = FALSE)
head(assay(vsd), 3)
```

```
##                    SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516
## ENSG00000000003.14  10.082167   9.828058  10.152774   9.970690  10.410407
## ENSG00000000419.12   9.663489   9.900634   9.779942   9.775148   9.740478
## ENSG00000000457.13   9.417376   9.280001   9.333639   9.430438   9.250501
##                    SRR1039517 SRR1039520 SRR1039521
## ENSG00000000003.14  10.171994  10.300682   9.976235
## ENSG00000000419.12   9.848458   9.659469   9.817695
## ENSG00000000457.13   9.363013   9.450889   9.444291
```

```
colData(vsd)
```

```
## DataFrame with 8 rows and 5 columns
##                 names    donor     condition     cell      dex
##              <factor> <factor>      <factor> <factor> <factor>
## SRR1039508 SRR1039508  N61311  Untreated      N61311     untrt
## SRR1039509 SRR1039509  N61311  Dexamethasone  N61311     trt  
## SRR1039512 SRR1039512  N052611 Untreated      N052611    untrt
## SRR1039513 SRR1039513  N052611 Dexamethasone  N052611    trt  
## SRR1039516 SRR1039516  N080611 Untreated      N080611    untrt
## SRR1039517 SRR1039517  N080611 Dexamethasone  N080611    trt  
## SRR1039520 SRR1039520  N061011 Untreated      N061011    untrt
## SRR1039521 SRR1039521  N061011 Dexamethasone  N061011    trt
```

و نیز برای _rlog_:

```
rld <- rlog(dds, blind = FALSE)
head(assay(rld), 3)
```

```
##                    SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516
## ENSG00000000003.14   9.479269   9.172988   9.561792   9.347935   9.853759
## ENSG00000000419.12   8.856681   9.150490   9.003390   8.997381   8.954032
## ENSG00000000457.13   8.352320   8.165586   8.239148   8.368679   8.122726
##                    SRR1039517 SRR1039520 SRR1039521
## ENSG00000000003.14   9.584201   9.730416   9.353458
## ENSG00000000419.12   9.088130   8.851863   9.049900
## ENSG00000000457.13   8.279323   8.396402   8.387635
```

در فراخوانی‌های تابعی بالا، `blind = FALSE` را مشخص کردیم؛ یعنی تفاوت‌های بین رده‌های سلولی و تیمار (متغیرهای موجود در طرح آزمایش) در شکل‌گیری روند مورد انتظارِ واریانس-میانگینِ این آزمایش مشارکت نخواهند داشت. طرح آزمایشی مستقیماً در خودِ تبدیل به‌کار نمی‌رود، بلکه فقط برای برآورد میزان کلیِ تغییرپذیریِ موجود در شمارش‌ها استفاده می‌شود. برای یک تبدیل کاملاً بدون ناظر، می‌توان `blind = TRUE` را تنظیم کرد (که پیش‌فرض نیز همین است).

برای نمایش اثر تبدیل، در شکل زیر نمونهٔ اول را در برابر نمونهٔ دوم رسم می‌کنیم: ابتدا با استفادهٔ ساده از تابع _log2_ (پس از افزودن 1 برای پرهیز از گرفتن لگاریتمِ صفر)، و سپس با استفاده از مقادیر تبدیل‌شده با VST و rlog. برای رویکرد _log2_ لازم است ابتدا ضریب‌های اندازه را برای درنظرگرفتن عمق توالی‌گزینی برآورد کنیم و سپس `normalized=TRUE` را مشخص کنیم. اصلاح عمق توالی‌گزینی برای _vst_ و _rlog_ به‌صورت خودکار انجام می‌شود.

```
library("dplyr")
library("ggplot2")

dds <- estimateSizeFactors(dds)

df <- bind_rows(
  as_data_frame(log2(counts(dds, normalized=TRUE)[, 1:2]+1)) %>%
         mutate(transformation = "log2(x + 1)"),
  as_data_frame(assay(vsd)[, 1:2]) %>% mutate(transformation = "vst"),
  as_data_frame(assay(rld)[, 1:2]) %>% mutate(transformation = "rlog"))
  
colnames(df)[1:2] <- c("x", "y")  

lvls <- c("log2(x + 1)", "vst", "rlog")
df$transformation <- factor(df$transformation, levels=lvls)

ggplot(df, aes(x = x, y = y)) + geom_hex(bins = 80) +
  coord_fixed() + facet_grid( . ~ transformation)
```

Scatterplot of transformed counts from two samples. نمودار پراکنشِ شمارش‌های تبدیل‌شده از دو نمونه. نمودارهای پراکنش با تبدیل لگاریتمی پایهٔ 2 روی شمارش‌های نرمال‌شده (چپ)، با VST (میانه)، و با rlog (راست) نشان داده شده‌اند. در حالی‌که rlog تقریباً روی همان مقیاسِ شمارش‌های لگاریتمی پایهٔ 2 است، VST برای مقادیر کوچک‌تر یک جابه‌جایی رو به بالا دارد. این تفاوت‌ها بین نمونه‌هاست (انحراف از y=x در این نمودارهای پراکنش) که به محاسبات فاصله و نمودار PCA سهم می‌افزایند.

می‌بینیم ژن‌هایی با شمارش‌های پایین (گوشهٔ پایین-چپ) روی مقیاس لگاریتمی معمول بیش‌ازحد متغیر به‌نظر می‌رسند، حال آن‌که VST و rlog اختلاف‌ها را برای ژن‌های کم‌شمارشی که داده‌ها دربارهٔ بیان تفاضلی آن‌ها اطلاعات اندکی فراهم می‌کنند، فشرده می‌سازند.

## ۴٫۳ فاصلهٔ نمونه‌ها

یک گام آغازینِ مفید در تحلیل RNA-seq اغلب ارزیابی شباهت کلی بین نمونه‌هاست: کدام نمونه‌ها به‌هم شبیه‌اند و کدام متفاوت؟ آیا این با انتظار برآمده از طرح آزمایش سازگار است؟

از تابع R به‌نام _dist_ برای محاسبهٔ فاصلهٔ اقلیدسی بین نمونه‌ها استفاده می‌کنیم. برای اطمینان از مشارکت تقریباً یکنواختِ همهٔ ژن‌ها، این تابع را بر داده‌های VST به‌کار می‌بریم. باید ماتریس مقادیر را با _t_ ترانهاده کنیم، زیرا تابع _dist_ انتظار دارد نمونه‌های مختلف سطرهای آرگومان آن باشند و ابعاد مختلف (اینجا ژن‌ها) در ستون‌ها قرار گیرند.

```
sampleDists <- dist(t(assay(vsd)))
sampleDists
```

```
##            SRR1039508 SRR1039509 SRR1039512 SRR1039513 SRR1039516 SRR1039517
## SRR1039509   37.77776                                                       
## SRR1039512   30.25948   43.38127                                            
## SRR1039513   49.66501   34.84097   40.18573                                 
## SRR1039516   33.62914   46.11028   32.89674   50.61885                      
## SRR1039517   50.13559   39.95782   45.59332   38.73688   38.49412           
## SRR1039520   29.92878   45.27463   27.72834   46.25456   34.97574   48.96752
## SRR1039521   50.08387   35.35988   45.51074   28.48458   51.19216   39.62934
##            SRR1039520
## SRR1039509           
## SRR1039512           
## SRR1039513           
## SRR1039516           
## SRR1039517           
## SRR1039520           
## SRR1039521   41.45015
```

فاصله‌ها را در شکل زیر به‌صورت نقشهٔ گرمایی ترسیم می‌کنیم، با استفاده از تابع _pheatmap_ از بستهٔ _[pheatmap](https://cran.r-project.org/package=pheatmap)_.

```
library("pheatmap")
library("RColorBrewer")
```

برای ترسیم ماتریس فاصلهٔ نمونه‌ها با آرایش ردیف‌ها/ستون‌ها بر پایهٔ فاصله‌های همین ماتریس، `sampleDists` را به آرگومان `clustering_distance` در تابع _pheatmap_ به‌صورت دستی می‌دهیم. در غیر این‌صورت، تابع _pheatmap_ فرض می‌کند ماتریس شامل خودِ مقادیر داده است و فاصله‌ها را بین ردیف‌ها/ستون‌های ماتریسِ فاصله دوباره محاسبه می‌کند، که مطلوب ما نیست. همچنین یک پالت رنگیِ آبی را به‌صورت دستی با تابع _colorRampPalette_ از بستهٔ _[RColorBrewer](https://cran.r-project.org/package=RColorBrewer)_ مشخص می‌کنیم.

```
sampleDistMatrix <- as.matrix( sampleDists )
rownames(sampleDistMatrix) <- paste( vsd$dex, vsd$cell, sep = " - " )
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colors)
```

Heatmap of sample-to-sample distances using the variance stabilizing transformed values. نقشهٔ گرماییِ فاصله‌های نمونه-به-نمونه با استفاده از مقادیر تبدیل‌شدهٔ پایدارکنندهٔ واریانس.

توجه کنید که نام سطرهای ماتریس فاصله را تغییر دادیم تا به‌جای شناسهٔ نمونه، نوع تیمار و شمارهٔ بیمار را شامل شود؛ تا هنگام مشاهدهٔ نقشهٔ گرمایی، همهٔ این اطلاعات در دسترس دید باشد.

گزینهٔ دیگری برای محاسبهٔ فاصله‌های نمونه‌ها استفاده از Poisson Distance (Witten 2011) است که در بستهٔ _[PoiClaClu](https://cran.r-project.org/package=PoiClaClu)_ پیاده‌سازی شده است. این معیارِ عدم شباهت بین شمارش‌ها، هنگام محاسبهٔ فاصله‌ها بین نمونه‌ها، ساختار واریانس ذاتیِ شمارش‌ها را نیز در نظر می‌گیرد. تابع _PoissonDistance_ ماتریس شمارشِ اصلی (نرنمال‌شده) را می‌پذیرد با این تفاوت که نمونه‌ها باید به‌جای ستون‌ها، سطرها باشند؛ بنابراین باید شمارش‌ها را در `dds` ترانهاده کنیم.

```
library("PoiClaClu")
poisd <- PoissonDistance(t(counts(dds)))
```

نقشهٔ گرمایی را در شکل زیر ترسیم می‌کنیم.

```
samplePoisDistMatrix <- as.matrix( poisd$dd )
rownames(samplePoisDistMatrix) <- paste( dds$dex, dds$cell, sep=" - " )
colnames(samplePoisDistMatrix) <- NULL
pheatmap(samplePoisDistMatrix,
         clustering_distance_rows = poisd$dd,
         clustering_distance_cols = poisd$dd,
         col = colors)
```

Heatmap of sample-to-sample distances using the _Poisson Distance_. نقشهٔ گرماییِ فاصله‌های نمونه-به-نمونه با استفاده از _Poisson Distance_.

## ۴٫۴ نمودار PCA

راه دیگر برای نمایش فاصله‌های نمونه-به-نمونه، تحلیل مؤلفه‌های اصلی (PCA) است. در این روش، نقاط داده (اینجا نمونه‌ها) روی صفحهٔ دوبعدی افکنده می‌شوند به‌طوری‌که در دو جهتی که بیشترین مقدارِ توضیحِ واریانس را دارند، بیشترین پراکنش را بیابند.
تفاوت‌ها (شکل زیر). محور x جهت تفکیک‌کننده‌ای است که بیشترین جدایی میان نقاط داده را فراهم می‌کند. مقادیر نمونه‌ها در این جهت با _PC1_ نشان داده می‌شوند. محور y جهت دیگری است (که باید نسبت به جهت اول _orthogonal_ باشد) که دومین بیشترین جدایی را ایجاد می‌کند. مقادیر نمونه‌ها در این جهت با _PC2_ نمایش داده می‌شوند. درصد واریانس کل که در هر جهت قرار دارد در برچسب محور نوشته شده است. توجه کنید که این درصدها با هم جمع‌شونده به 100٪ نمی‌شوند، چون ابعاد دیگری هم وجود دارند که واریانس باقی‌مانده را در خود دارند (گرچه هر یک از این ابعاد باقیمانده کمتر از دو بعدی خواهند بود که می‌بینیم).

```
plotPCA(vsd, intgroup = c("dex", "cell"))
```

**PCA plot using the VST data.** به هر ترکیب منحصربه‌فرد از درمان و ردهٔ سلولی رنگ متفاوتی اختصاص داده شده است.

در اینجا از تابع _plotPCA_ که همراه با _DESeq2_ ارائه می‌شود استفاده کرده‌ایم. دو عبارتی که توسط `intgroup` مشخص شده‌اند، گروه‌های مورد نظر برای برچسب‌گذاری نمونه‌ها هستند؛ این عبارات به تابع می‌گویند که از آن‌ها برای انتخاب رنگ‌ها استفاده کند. همچنین می‌توانیم نمودار PCA را از ابتدا با استفاده از بستهٔ _[ggplot2](https://cran.r-project.org/package=ggplot2)_ بسازیم (Wickham 2009). برای این کار، از تابع _plotPCA_ می‌خواهیم که به‌جای ساختن نمودار، داده‌های مورد استفاده برای رسم را برگرداند. برای جزئیات بیشتر دربارهٔ استفاده از _ggplot_ به مستندات _ggplot2_ مراجعه کنید: http://docs.ggplot2.org/current/.

```
pcaData <- plotPCA(vsd, intgroup = c( "dex", "cell"), returnData = TRUE)
pcaData
```

```
##                   PC1       PC2         group       name      names   donor
## SRR1039508 -14.427794 -3.057906  untrt:N61311 SRR1039508 SRR1039508  N61311
## SRR1039509   8.144808 -1.422929    trt:N61311 SRR1039509 SRR1039509  N61311
## SRR1039512  -9.476223 -4.414224 untrt:N052611 SRR1039512 SRR1039512 N052611
## SRR1039513  14.628644 -4.290437   trt:N052611 SRR1039513 SRR1039513 N052611
## SRR1039516 -12.425251 11.397272 untrt:N080611 SRR1039516 SRR1039516 N080611
## SRR1039517   9.475669 15.097249   trt:N080611 SRR1039517 SRR1039517 N080611
## SRR1039520 -10.965862 -7.197057 untrt:N061011 SRR1039520 SRR1039520 N061011
## SRR1039521  15.046009 -6.111969   trt:N061011 SRR1039521 SRR1039521 N061011
##                condition    cell   dex
## SRR1039508     Untreated  N61311 untrt
## SRR1039509 Dexamethasone  N61311   trt
## SRR1039512     Untreated N052611 untrt
## SRR1039513 Dexamethasone N052611   trt
## SRR1039516     Untreated N080611 untrt
## SRR1039517 Dexamethasone N080611   trt
## SRR1039520     Untreated N061011 untrt
## SRR1039521 Dexamethasone N061011   trt
```

```
percentVar <- round(100 * attr(pcaData, "percentVar"))
```

سپس می‌توانیم از این داده‌ها برای ساختن یک نمودار دوم در شکل زیر استفاده کنیم، طوری که رنگ نقاط نشان‌دهندهٔ درمان با دگزامتازون و شکل نمادها نشان‌دهندهٔ ردهٔ سلولی باشد.

```
ggplot(pcaData, aes(x = PC1, y = PC2, color = dex, shape = cell)) +
  geom_point(size =3) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
  coord_fixed() +
  ggtitle("PCA with VST data")
```

**PCA plot using the VST values with custom _ggplot2_ code.** در اینجا ردهٔ سلولی (نماد رسم) و درمان با دگزامتازون (رنگ) مشخص شده‌اند.

از نمودار PCA می‌بینیم که اختلافات بین سلول‌ها (شکل‌های رسم متفاوت) چشمگیر هستند، اگرچه قدرتمندتر از اختلافات ناشی از درمان با دگزامتازون (قرمز در مقابل آبی) نیستند. این نشان می‌دهد که در آزمون‌های تفاضلی لازم است این موضوع را با طراحی زوجی (paired)، یعنی جفت‌کردن، در نظر بگیریم چون هر نمونهٔ درمان‌شده با دگزامتازون با یک نمونهٔ بدون درمان از همان ردهٔ سلولی «جفت» شده است. ما قبلاً برای این طراحی آماده شده‌ایم چون فرمول `~ cell + dex` را قبلاً اختصاص داده‌ایم.

## ۴٫۵ نمودار PCA با استفاده از PCA تعمیم‌یافته

یک روش دیگر برای کاهش بعد در داده‌هایی که توزیع نرمال ندارند (مثلاً داده‌های شمارش که بیش‌پراکنش دارند) استفاده از generalized principal component analysis یا GLM-PCA است (Townes و همکاران، 2019) که در بستهٔ CRAN _[glmpca](https://cran.r-project.org/package=glmpca)_ پیاده‌سازی شده است. این بسته ماتریس شمارش (count (شمارش)) را به‌عنوان ورودی می‌گیرد و همچنین تعداد ابعاد نهفته‌ای را که باید برازش شوند (در اینجا 2) می‌پذیرد. همان‌طور که Townes و همکاران (2019) بیان می‌کنند:

> …ما پیشنهاد می‌کنیم از GLM-PCA استفاده شود، که تعمیمی از
> PCA برای توزیع‌های خانوادهٔ نمایی است. GLM-PCA بر روی شمارش‌های خام عمل می‌کند
> و از مشکلات مربوط به نرمال‌سازی (normalization (نرمال‌سازی)) اجتناب می‌نماید. همچنین نشان می‌دهیم که به‌کارگیری PCA
> روی باقیمانده‌های deviance یا Pearson تقریب سودمند و سریعی از
> GLM-PCA ارائه می‌دهد.

```
library("glmpca")
gpca <- glmpca(counts(dds), L=2)
gpca.dat <- gpca$factors
gpca.dat$dex <- dds$dex
gpca.dat$cell <- dds$cell
```

```
ggplot(gpca.dat, aes(x = dim1, y = dim2, color = dex, shape = cell)) +
  geom_point(size =3) + coord_fixed() + ggtitle("glmpca - Generalized PCA")
```

## ۴٫۶ نمودار MDS

نمودار دیگری، بسیار شبیه به نمودار PCA، را می‌توان با استفاده از تابع _multidimensional scaling_ (MDS) در R پایه ساخت. این روش زمانی مفید است که ماتریس داده در اختیار نداریم و تنها یک ماتریس فواصل داریم. در اینجا ما MDS را برای فواصل محاسبه‌شده از داده‌های _VST_ محاسبه می‌کنیم و آن‌ها را در شکل زیر رسم می‌کنیم.

```
mds <- as.data.frame(colData(vsd))  %>%
         cbind(cmdscale(sampleDistMatrix))
ggplot(mds, aes(x = `1`, y = `2`, color = dex, shape = cell)) +
  geom_point(size = 3) + coord_fixed() + ggtitle("MDS with VST data")
```

**MDS plot using VST data.**

در شکل زیر همان نمودار را برای _PoissonDistance_ نشان داده‌ایم:

```
mdsPois <- as.data.frame(colData(dds)) %>%
   cbind(cmdscale(samplePoisDistMatrix))
ggplot(mdsPois, aes(x = `1`, y = `2`, color = dex, shape = cell)) +
  geom_point(size = 3) + coord_fixed() + ggtitle("MDS with PoissonDistances")
```

**MDS plot using the _Poisson Distance_ .**

# ۵ differential expression analysis (تحلیل بیان تفاضلی)

## ۵٫۱ اجرای خط لولهٔ تحلیل بیان تفاضلی

چون هنگام ساخت _DESeqDataSet_ طراحی تجربی را تعیین کرده‌ایم، می‌توانیم خط لولهٔ تحلیل بیان تفاضلی را روی شمارش‌های خام با یک فراخوانی به تابع _DESeq_ اجرا کنیم:

```
dds <- DESeq(dds)
```

این تابع در هر مرحله پیام‌هایی دربارهٔ عملیات انجام‌شده چاپ می‌کند. این مراحل در صفحهٔ راهنمای تابع _DESeq_ که با تایپ `?DESeq` قابل دسترسی است، مفصل‌تر شرح داده شده‌اند. به‌طور خلاصه، این مراحل عبارت‌اند از: برآورد size factors (کنترل اختلاف در عمق توالی‌یابی نمونه‌ها)، برآورد مقدارهای dispersion (پراکندگی) برای هر gene (ژن)، و برازش یک مدل خطی تعمیم‌یافته.

یک _DESeqDataSet_ بازگردانده می‌شود که شامل همهٔ پارامترهای برازش‌یافته در خود است، و بخش بعدی شرح می‌دهد چگونه جداول نتایج مورد علاقه را از این شی استخراج کنیم.

## ۵٫۲ ساخت جدول نتایج

فراخوانی _results_ بدون هیچ آرگومانی، برآوردهای log2 fold change و مقادیر p را برای آخرین متغیر در فرمول طراحی استخراج می‌کند. اگر برای این متغیر بیش از دو سطح وجود داشته باشد، _results_ جدول نتایج مقایسهٔ سطح آخر نسبت به سطح اول را استخراج خواهد کرد. مقایسه در بالای خروجی چاپ می‌شود: `dex trt vs untrt` .

```
res <- results(dds)
res
```

```
## log2 fold change (MLE): dex trt vs untrt 
## Wald test p-value: dex trt vs untrt 
## DataFrame with 16637 rows and 6 columns
##                     baseMean log2FoldChange     lfcSE      stat      pvalue
##                    <numeric>      <numeric> <numeric> <numeric>   <numeric>
## ENSG00000000003.14  740.1093      -0.365327 0.1073385 -3.403501 6.65282e-04
## ENSG00000000419.12  511.6990       0.202232 0.1278579  1.581694 1.13720e-01
## ENSG00000000457.13  314.1680       0.033792 0.1552106  0.217717 8.27650e-01
## ENSG00000000460.16   79.7988      -0.120633 0.3055270 -0.394836 6.92964e-01
## ENSG00000000971.15 5715.3064       0.442982 0.0904089  4.899766 9.59508e-07
## ...                      ...            ...       ...       ...         ...
## ENSG00000285953.1    29.5747      -1.920562  0.649661 -2.956253  0.00311401
## ENSG00000285967.1   181.1650      -0.325885  0.179340 -1.817132  0.06919688
## ENSG00000285976.1   875.4424       0.262132  0.142980  1.833351  0.06675037
## ENSG00000285979.1    38.3502       0.338383  0.348445  0.971124  0.33148631
## ENSG00000285991.1    11.2772      -0.115472  0.723139 -0.159681  0.87313221
##                           padj
##                      <numeric>
## ENSG00000000003.14 4.63552e-03
## ENSG00000000419.12 2.88125e-01
## ENSG00000000457.13 9.21718e-01
## ENSG00000000460.16 8.48743e-01
## ENSG00000000971.15 1.36387e-05
## ...                        ...
## ENSG00000285953.1    0.0171889
## ENSG00000285967.1    0.2019448
## ENSG00000285976.1    0.1965808
## ENSG00000285979.1    0.5713913
## ENSG00000285991.1           NA
```

ما می‌توانستیم همین جدول نتایج را با فرمان مشخص‌تری نیز تولید کنیم. چون `dex` آخرین متغیر در طراحی است، می‌توانیم به‌طور اختیاری آرگومان `contrast` را حذف کنیم تا مقایسهٔ دو سطح `dex` را استخراج نماییم.

```
res <- results(dds, contrast=c("dex","trt","untrt"))
```

چون `res` یک شیء _DataFrame_ است، متادیتایی را که معنی ستون‌ها را توضیح می‌دهد همراه دارد:

```
mcols(res, use.names = TRUE)
```

```
## DataFrame with 6 rows and 2 columns
##                        type            description
##                 <character>            <character>
## baseMean       intermediate mean of normalized c..
## log2FoldChange      results log2 fold change (ML..
## lfcSE               results standard error: dex ..
## stat                results Wald statistic: dex ..
## pvalue              results Wald test p-value: d..
## padj                results   BH adjusted p-values
```

ستون اول، `baseMean`، صرفاً میانگین مقادیر شمارش نرمال‌شده (normalized count (شمارش) values)، تقسیم بر size factors، گرفته‌شده بر روی تمام نمونه‌ها در _DESeqDataSet_ است. چهار ستون باقیمانده به یک contrast (مقایسه) مشخص اشاره دارند، یعنی مقایسهٔ سطح `trt` نسبت به سطح `untrt` برای متغیر فاکتوری `dex`. در بخش‌های بعدی خواهیم دید چگونه مقایسه‌های دیگر را به‌دست آوریم.

ستون `log2FoldChange` برآورد اندازهٔ اثر است. این ستون نشان می‌دهد که بیان ژن (gene (ژن)) تا چه حد به‌نظر می‌رسد بر اثر درمان با دگزامتازون نسبت به نمونه‌های بدون درمان تغییر کرده است. این مقدار روی مقیاس لگاریتمی پایهٔ 2 گزارش می‌شود: برای مثال، یک log2 fold change برابر 1.5 یعنی بیان ژن حدوداً به‌مقدار ضریب 2^{1.5} ≈ 2.82 افزایش یافته است.

بدیهی است که این برآورد با عدم‌قطعیتی همراه است، که در ستون `lfcSE` در دسترس است؛ این ستون برآورد خطای استاندارد برای برآورد log2 fold change را نشان می‌دهد. همچنین می‌توان عدم‌قطعیت یک برآورد اندازهٔ اثر را به‌صورت نتیجهٔ یک آزمون آماری بیان کرد. هدف از یک آزمون برای تحلیل بیان تفاضلی (تحلیل بیان تفاضلی) این است که بررسی کند آیا داده‌ها شواهد کافی برای نتیجه‌گیری دربارهٔ اینکه این ...
مقدار واقعاً از صفر متفاوت است. _DESeq2_ برای هر gene (ژن) یک آزمون فرضیه انجام می‌دهد تا بررسی کند آیا شواهد برای رد null hypothesis (فرض صفر) — که می‌گوید درمان بر gene (ژن) تأثیری ندارد — کافی هست یا خیر؛ در غیر این صورت تفاوت مشاهده‌شده بین گروه درمان و کنترل صرفاً ناشی از تغییرات تجربی است (یعنی همان نوع نوسانی که بین نمونه‌های مختلف در یک گروه درمانی انتظار می‌رود). همان‌طور که در آمار معمول است، نتیجهٔ این آزمون به‌صورت یک p value گزارش می‌شود و در ستون `pvalue` قرار دارد. به‌خاطر داشته باشید که p value نشان‌دهندهٔ احتمال مشاهدهٔ تغییر توانی (fold change)‌ای به‌اندازهٔ مقدار مشاهده‌شده یا قوی‌تر، تحت مفروضات فرض صفر است.

می‌توانیم نتایج را همچنین با خط کد زیر خلاصه کنیم؛ این خط اطلاعات اضافی‌ای گزارش می‌دهد که در بخش‌های بعد پوشش داده خواهد شد.

```
summary(res)
```

```
## 
## out of 16637 with nonzero total read count
## adjusted p-value < 0.1
## LFC > 0 (up)       : 2362, 14%
## LFC < 0 (down)     : 2019, 12%
## outliers [1]       : 0, 0%
## low counts [2]     : 646, 3.9%
## (mean count < 12)
## [1] see 'cooksCutoff' argument of ?results
## [2] see 'independentFiltering' argument of ?results
```

توجه کنید که در سطح false discovery rate (نرخ کشف کاذب) برابر 10%، تعداد زیادی gene (ژن) نشان‌دهندهٔ differential expression analysis (تحلیل بیان تفاضلی) در پاسخ به درمان با دگزامتازون هستند. این نتیجه معقول است، زیرا سلول‌های ماهیچهٔ صاف راه‌های هوایی به گلوکوکورتیکوئیدها شناخته‌شده واکنش نشان می‌دهند. با این حال دو راه برای محدودتر کردن مجموعهٔ ژن‌های مورد نظر به‌عنوان قابل‌توجه وجود دارد:

* کاهش آستانهٔ نرخ کشف کاذب (آستانهٔ ستون `padj` در جدول نتایج)
* افزایش آستانهٔ log2 fold change از 0 با استفاده از آرگومان `lfcThreshold` در تابع _results_

اگر آستانهٔ نرخ کشف کاذب را پایین‌تر ببریم، باید این آستانه را به تابع `results()` اطلاع دهیم تا آن تابع بتواند از این آستانه در فرایند فیلترینگ مستقلِ بهینه‌اش استفاده کند:

```
res.05 <- results(dds, alpha = 0.05)
table(res.05$padj < 0.05)
```

```
## 
## FALSE  TRUE 
## 12712  3602
```

اگر بخواهیم آستانهٔ log2 fold change را بالا ببریم تا فقط به ژن‌هایی توجه کنیم که تغییرات بزرگ‌تری در پاسخ به درمان نشان می‌دهند، کافی است مقداری را بر روی مقیاس log2 تعیین کنیم. برای مثال با مشخص کردن `lfcThreshold = 1`، ما برای ژن‌هایی آزمون می‌کنیم که اثرات معناداری از درمان بر gene (ژن) count (شمارش) نشان می‌دهند که بیش از دو برابر شدن یا کمتر از نصف شدن هستند، زیرا \\(2^1 = 2\\).

```
resLFC1 <- results(dds, lfcThreshold=1)
table(resLFC1$padj < 0.1)
```

```
## 
## FALSE  TRUE 
## 16397   240
```

گاهی زیرمجموعه‌ای از p values در `res` دارای مقدار `NA` («not available») خواهند بود. این روش _DESeq_ برای گزارش این وضعیت است که تمام شمارش‌ها برای آن gene (ژن) صفر بوده‌اند و بنابراین هیچ آزمونی اعمال نشده است. علاوه بر این، p values ممکن است `NA` اختصاص یابند اگر یک ژن از تحلیل حذف شده باشد چون شامل یک مقدار بیرونی بسیار دور از سایر شمارش‌ها بوده است. برای اطلاعات بیشتر، بخش شناسایی مقادیر بیرونی در وینیِت _DESeq2_ را ببینید.

اگر از نتایج یک بستهٔ آنالیز R در پژوهش منتشرشده استفاده می‌کنید، می‌توانید ارجاع مناسب نرم‌افزار را با تایپ `citation("pkgName")` بیابید؛ در آنجا باید نام بسته را به‌جای `pkgName` قرار دهید. ارجاع دادن به مقالات روش‌شناسی به حمایت و پاداش دادن به افرادی که وقت صرف توسعهٔ نرم‌افزار متن‌باز برای تحلیل داده‌های ژنومی کرده‌اند کمک می‌کند.

## ۵٫۳ مقایسه‌های دیگر

به‌طور کلی، نتایج مربوط به مقایسهٔ هر دو سطحِ یک متغیر را می‌توان با استفاده از آرگومان `contrast` در تابع _results_ استخراج کرد. کاربر باید سه مقدار را مشخص کند: نام متغیر، نام سطحِ صورت‌گر (صورت‌مقام) و نام سطحِ مخرج. در اینجا نتایج برای log2 fold change یک خط سلولی نسبت به خط سلولی دیگر را استخراج می‌کنیم:

```
results(dds, contrast = c("cell", "N061011", "N61311"))
```

```
## log2 fold change (MLE): cell N061011 vs N61311 
## Wald test p-value: cell N061011 vs N61311 
## DataFrame with 16637 rows and 6 columns
##                     baseMean log2FoldChange     lfcSE      stat      pvalue
##                    <numeric>      <numeric> <numeric> <numeric>   <numeric>
## ENSG00000000003.14  740.1093      0.2725914  0.152831  1.783618 7.44857e-02
## ENSG00000000419.12  511.6990     -0.0707901  0.181681 -0.389640 6.96803e-01
## ENSG00000000457.13  314.1680      0.1816517  0.220300  0.824567 4.09618e-01
## ENSG00000000460.16   79.7988     -0.1180515  0.428104 -0.275754 7.82737e-01
## ENSG00000000971.15 5715.3064      0.8234461  0.128134  6.426459 1.30610e-10
## ...                      ...            ...       ...       ...         ...
## ENSG00000285953.1    29.5747      1.3094223  0.891768  1.468344   0.1420107
## ENSG00000285967.1   181.1650     -0.5347871  0.254739 -2.099355   0.0357856
## ENSG00000285976.1   875.4424     -0.0932084  0.202503 -0.460281   0.6453144
## ENSG00000285979.1    38.3502      0.0604501  0.496866  0.121663   0.9031662
## ENSG00000285991.1    11.2772     -0.8779643  1.010832 -0.868556   0.3850901
##                           padj
##                      <numeric>
## ENSG00000000003.14 3.72420e-01
## ENSG00000000419.12 9.34643e-01
## ENSG00000000457.13 8.04500e-01
## ENSG00000000460.16 9.57685e-01
## ENSG00000000971.15 1.61144e-08
## ...                        ...
## ENSG00000285953.1     0.517887
## ENSG00000285967.1     0.241459
## ENSG00000285976.1     0.916522
## ENSG00000285979.1     0.981312
## ENSG00000285991.1           NA
```

پس از اجرای _DESeq_ یک بار، راه‌های اضافی‌ای برای ساخت جداول نتایج برای برخی مقایسه‌ها وجود دارد. اگر نتایج برای یک ترمِ تعامل (interaction) مورد نیاز باشد، باید از آرگومان `name` در _results_ استفاده کنید. برای جزئیات بیشتر به صفحهٔ راهنمای تابع _results_ مراجعه کنید؛ بخش Examples در آن صفحه مثال‌های مرتبطی ارائه می‌دهد.

## ۵٫۴ multiple testing (آزمون‌های چندگانه)

در زیست‌شناسی با توان بالا، احتیاط می‌کنیم که از p values مستقیماً به‌عنوان شواهد علیه فرض صفر استفاده نکنیم و در عوض برای اصلاح multiple testing (آزمون‌های چندگانه) اقدام نماییم. اگر بخواهیم به‌سادگی p values را در آستانهٔ کمی، مثلاً 0.05، محدود کنیم چه اتفاقی می‌افتد؟ از بین 16637 gene (ژن) که آزمون برای آن‌ها قادر به گزارش p value بود، 5069 gene (ژن) دارای p value کمتر از 0.05 هستند:

```
sum(res$pvalue < 0.05, na.rm=TRUE)
```

```
## [1] 5069
```

```
sum(!is.na(res$pvalue))
```

```
## [1] 16637
```

اکنون فرض کنید برای لحظه‌ای که فرض صفر برای همهٔ ژن‌ها برقرار است، یعنی هیچ ژنی توسط درمان دگزامتازون تحت تأثیر قرار نگرفته است. آنگاه طبق تعریف p value، انتظار داریم تا 5% از ژن‌ها مقدار p پایین‌تر از 0.05 داشته باشند؛ این معادل 832 ژن است. اگر صرفاً فهرست ژن‌هایی را که p value آن‌ها کمتر از 0.05 است به‌عنوان دارای بیان تفاضلی در نظر بگیریم، این فهرست بنابراین انتظار می‌رود شامل تا 832 / 5069 = 16% نتایج مثبت کاذب باشد.

_DESeq2_ از اصلاح بنجامینی-هوچبرگ (Benjamini-Hochberg, BH) که در تابع پایهٔ R به نام _p.adjust_ پیاده‌سازی شده است استفاده می‌کند؛ به‌اختصار، این روش برای هر ژن یک adjusted p-value (مقدار p تعدیل‌شده) محاسبه می‌کند که به سوال زیر پاسخ می‌دهد: اگر همهٔ ژن‌هایی را که مقدار p تعدیل‌شدهٔ آن‌ها کمتر یا برابر آستانهٔ مقدار p تعدیل‌شدهٔ این ژن باشند را «معنادار» فرض کنیم، چه کسری از آن‌ها مثبت کاذب خواهند بود (false discovery rate) با محاسبه‌ای مشابه آنچه پیش‌تر توضیح داده شد؟ این مقادیر، که BH-adjusted p values نامیده می‌شوند، در ستون `padj` شیٔ `res` قرار دارند.

نرخ کشف کاذب برای بسیاری از آزمایش‌های با توان بالا آمار مفیدی است، چون اغلب علاقه‌مند به گزارش یا تمرکز بر یک مجموعهٔ مشخص از ژن‌های جالب هستیم و می‌خواهیم یک کرانهٔ بالایی برای درصد نتایج مثبت کاذب در این مجموعه تعیین کنیم.

بنابراین، اگر یک کسر 10% نتایج مثبت کاذب قابل‌قبول بدانیم، می‌توانیم همهٔ ژن‌هایی را که مقدار p تعدیل‌شدهٔ آن‌ها کمتر از 10% = 0.1 است به‌عنوان معنادار در نظر بگیریم. تعداد این ژن‌ها چقدر است؟

```
sum(res$padj < 0.1, na.rm=TRUE)
```

```
## [1] 4381
```

جدول نتایج را به این ژن‌ها زیرمجموعه‌گیری کرده و سپس بر اساس برآورد log2 fold change مرتب می‌کنیم تا ژن‌های معنادار با شدتِ بیشترین کاهش بیان را به‌دست آوریم:

```
resSig <- subset(res, padj < 0.1)
head(resSig[ order(resSig$log2FoldChange), ])
```

```
## log2 fold change (MLE): dex trt vs untrt 
## Wald test p-value: dex trt vs untrt 
## DataFrame with 6 rows and 6 columns
##                     baseMean log2FoldChange     lfcSE      stat      pvalue
##                    <numeric>      <numeric> <numeric> <numeric>   <numeric>
## ENSG00000216490.3    42.3457       -5.72709  1.474282  -3.88466 1.02473e-04
## ENSG00000267339.5    30.5903       -5.39692  0.754323  -7.15465 8.38861e-13
## ENSG00000146006.7    61.6555       -4.48259  0.643341  -6.96767 3.22240e-12
## ENSG00000155897.9    23.9892       -3.87698  0.809195  -4.79115 1.65824e-06
## ENSG00000213240.8    12.1002       -3.79153  1.221385  -3.10429 1.90737e-03
## ENSG00000162692.11  505.5613       -3.67636  0.201427 -18.25164 2.00779e-74
##                           padj
##                      <numeric>
## ENSG00000216490.3  9.14426e-04
## ENSG00000267339.5  2.76013e-11
## ENSG00000146006.7  9.83385e-11
## ENSG00000155897.9  2.25676e-05
## ENSG00000213240.8  1.14064e-02
## ENSG00000162692.11 2.00666e-71
```

…و برای بیشترین افزایش بیان:

```
head(resSig[ order(resSig$log2FoldChange, decreasing = TRUE), ])
```

```
## log2 fold change (MLE): dex trt vs untrt 
## Wald test p-value: dex trt vs untrt 
## DataFrame with 6 rows and 6 columns
##                     baseMean log2FoldChange     lfcSE      stat      pvalue
##                    <numeric>      <numeric> <numeric> <numeric>   <numeric>
## ENSG00000254692.1    62.1517       10.20327  3.377058   3.02135 2.51651e-03
## ENSG00000179593.15   66.9666        9.50105  1.070620   8.87435 7.03444e-19
## ENSG00000224712.12   35.5516        7.16466  2.164701   3.30977 9.33725e-04
## ENSG00000109906.13  437.5025        6.37252  0.309988  20.55731 6.62052e-94
## ENSG00000257663.1    24.3615        6.34094  2.094868   3.02689 2.47081e-03
## ENSG00000250978.5    45.6682        5.91333  0.710469   8.32314 8.56661e-17
##                           padj
##                      <numeric>
## ENSG00000254692.1  1.44165e-02
## ENSG00000179593.15 4.22886e-17
## ENSG00000224712.12 6.18525e-03
## ENSG00000109906.13 1.17632e-90
## ENSG00000257663.1  1.42176e-02
## ENSG00000250978.5  4.32141e-15
```

# ۶ ترسیم نتایج

## ۶٫۱ نمودار شمارش‌ها

یک روش سریع برای دیدن شمارش‌ها برای یک gene (ژن) خاص استفاده از تابع _plotCounts_ است که آرگومان‌های آن عبارت‌اند از یک _DESeqDataSet_، نام ژن و گروهی که بر اساس آن شمارش‌ها رسم خواهد شد (شکل زیر).

```
topGene <- rownames(res)[which.min(res$padj)]
plotCounts(dds, gene = topGene, intgroup=c("dex"))
```

**شمارش‌های نرمال‌شده برای یک ژن منفرد در گروه‌های درمان.**

همچنین می‌توانیم نمودارهای سفارشی با استفاده از تابع _ggplot_ از بستهٔ _[ggplot2](https://cran.r-project.org/package=ggplot2)_ بسازیم (اشکال زیر).

```
library("ggbeeswarm")
geneCounts <- plotCounts(dds, gene = topGene, intgroup = c("dex","cell"),
                         returnData = TRUE)
ggplot(geneCounts, aes(x = dex, y = count, color = cell)) +
  scale_y_log10() +  geom_beeswarm(cex = 3)
```

```
ggplot(geneCounts, aes(x = dex, y = count, color = cell, group = cell)) +
  scale_y_log10() + geom_point(size = 3) + geom_line()
```
**شمارش‌های normalization (نرمال‌سازی) شده با خطوطی که خطوط سلولی را به هم وصل می‌کنند.** توجه داشته باشید که آزمون _DESeq_ در واقع اثر خط سلولی را در نظر می‌گیرد، بنابراین این شکل تصویر دقیق‌تری از اختلافی که مورد آزمایش است ارائه می‌دهد.

## ۶٫۲ نمودار MA

یک _نمودار MA_ (Dudoit et al. 2002) نمای کلی مفیدی از توزیع ضرایب برآوردشده در مدل، مانند مقایسه‌های موردِ علاقه، در میان همه gene (ژن) فراهم می‌آورد. در محور عمودی، «M» از «minus» گرفته شده — تفریق مقادیر لگاریتمی معادل لگاریتمِ نسبت است — و در محور افقی، «A» از «average» گرفته شده است. ممکن است این نمودار را همچنین به‌عنوان یک نمودار میانگین-تفاوت یا نمودار بلاند-آلتمن بشناسید.

پیش از رسم _نمودار MA_، از تابع _lfcShrink_ برای کوچک‌سازی (shrink) تغییرات لگاریتمی دو‌برابر (log2 fold changes) در مقایسه نمونه‌های درمان‌شده با dex در برابر نمونه‌های درمان‌نشده استفاده می‌کنیم. در _DESeq2_ سه نوع برآوردگر کوچک‌سازی وجود دارد که در [DESeq2 vignette](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html) پوشش داده شده‌اند. در اینجا روش _apeglm_ را برای کوچک‌سازی ضرایب مشخص می‌کنیم، روشی که برای کاهش نویز برآوردهای LFC مناسب است و در عین حال برای اختلافات واقعی بزرگ برآوردهای با بایاس کم تولید می‌کند (Zhu, Ibrahim, and Love 2018). برای استفاده از _apeglm_ باید یک ضریب از مدل را برای کوچک‌سازی مشخص کنیم، یا با نام یا با شماره‌ای که ضریب در `resultsNames(dds)` ظاهر می‌شود.

```
library("apeglm")
resultsNames(dds)
```

```
## [1] "Intercept"               "cell_N061011_vs_N052611"
## [3] "cell_N080611_vs_N052611" "cell_N61311_vs_N052611" 
## [5] "dex_trt_vs_untrt"
```

```
res <- lfcShrink(dds, coef="dex_trt_vs_untrt", type="apeglm")
plotMA(res, ylim = c(-5, 5))
```

اگر لازم باشد که یک contrast (مقایسه) که در `resultsNames(dds)` نشان داده نشده را مشخص کنیم، می‌توان از هر یک از دو روش کوچک‌سازی دیگر استفاده کرد، یا در برخی موارد بازتعریف متغیرهای مربوطه و اجرای `nbinomWaldTest` و سپس `lfcShrink` کافی است. برای جزئیات بیشتر به vignette مربوط به DESeq2 مراجعه کنید.

```
res.noshr <- results(dds, name="dex_trt_vs_untrt")
plotMA(res.noshr, ylim = c(-5, 5))
```

ما همچنین می‌توانیم نقاط منفرد را روی _نمودار MA_ برچسب‌گذاری کنیم. در اینجا از تابع _with_ در R برای رسم یک دایره و متن برای یک ردیف انتخاب‌شده از شیء نتایج استفاده می‌کنیم. درون تابع _with_ تنها مقادیر `baseMean` و `log2FoldChange` برای ردیف‌های انتخاب‌شده از `res` به کار می‌روند.

```
plotMA(res, ylim = c(-5,5))
topGene <- rownames(res)[which.min(res$padj)]
with(res[topGene, ], {
  points(baseMean, log2FoldChange, col="dodgerblue", cex=2, lwd=2)
  text(baseMean, log2FoldChange, topGene, pos=2, col="dodgerblue")
})
```

یکی دیگر از نمودارهای تشخیصی مفید، هیستوگرام مقادیر _p_ است (شکل زیر). این نمودار بهتر است با حذف ژن‌هایی که شمارش‌های بسیار کوچکی دارند ساخته شود، زیرا در غیر این صورت باعث ایجاد قله‌هایی در هیستوگرام می‌شوند.

```
hist(res$pvalue[res$baseMean > 1], breaks = 0:20/20,
     col = "grey50", border = "white")
```

**هیستوگرام مقادیر _p_ برای ژن‌هایی که میانگین شمارش normalization (نرمال‌سازی) شده آن‌ها بزرگ‌تر از 1 است.**

## ۶٫۳ خوشه‌بندی ژن‌ها

در نقشه گرمایی فواصل نمونه که پیش‌تر ساخته شد، دندروگرام در کنار نشان‌دهنده خوشه‌بندی سلسله‌مراتبی نمونه‌هاست. چنین خوشه‌بندی‌ای را می‌توان برای ژن‌ها نیز انجام داد. از آنجا که خوشه‌بندی تنها برای ژن‌هایی معنی‌دار است که واقعاً سیگنال دارند، معمولاً تنها زیرمجموعه‌ای از پر‌تغییرترین ژن‌ها را خوشه‌بندی می‌کنند. برای نمایش، بیایید 20 ژنی را انتخاب کنیم که بیشترین واریانس را در میان نمونه‌ها دارند. برای این کار از داده‌های VST استفاده خواهیم کرد.

```
library("genefilter")
topVarGenes <- head(order(rowVars(assay(vsd)), decreasing = TRUE), 20)
```

نقشهٔ گرمایی زمانی جالب‌تر می‌شود که به جای قدر مطلقِ میزان بیان، به میزان انحراف هر ژن در یک نمونه خاص از میانگین آن ژن در تمام نمونه‌ها نگاه کنیم. بنابراین، مقادیر هر ژن را در میان نمونه‌ها مرکزی (center) می‌کنیم و یک نقشهٔ گرمایی رسم می‌کنیم (شکل زیر). ما یک _data.frame_ فراهم می‌کنیم که به تابع _pheatmap_ می‌گوید چگونه ستون‌ها را برچسب‌گذاری کند.

```
mat  <- assay(vsd)[ topVarGenes, ]
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(vsd)[, c("cell","dex")])
pheatmap(mat, annotation_col = anno)
```

**نقشهٔ گرماییِ مقادیر تبدیل‌شده توسط VST به صورت نسبی در میان نمونه‌ها.** وضعیت درمان و اطلاعات خط سلولی با میله‌های رنگی در بالای نقشهٔ گرمایی نشان داده شده‌اند. بلوک‌هایی از ژن‌ها که به صورت هم‌تغییر در بین بیماران ظاهر می‌شوند دیده می‌شوند. توجه داشته باشید که مجموعه‌ای از ژن‌ها در نقشهٔ گرمایی خط سلولی N061011 را از بقیه جدا می‌کنند، و مجموعهٔ دیگری از ژن‌ها وجود دارد که در آن‌ها نمونه‌های درمان‌شده با دگزامتازون بیان ژن بالاتری دارند.

## ۶٫۴ پالایش مستقل

_n نمودار MA _ ویژگی مهمی از داده‌های RNA-seq را برجسته می‌کند. برای ژن‌هایی که ضعیف بیان می‌شوند، شانس دیدن differential expression analysis (تحلیل بیان تفاضلی) عملاً وجود ندارد، زیرا شمارش‌های کمِ read (خوانش) از نویز پواسونِ بسیار بالایی رنج می‌برند به‌طوری که هر اثر زیستی در عدم‌قطعیت‌های نمونه‌برداریِ با نرخ پایین غرق می‌شود. این موضوع را می‌توان با بررسی نسبت مقادیر _p_ کوچک (مثلاً کمتر از 0.05) برای ژن‌هایی که بر اساس میانگین شمارش normalization (نرمال‌سازی) شده دسته‌بندی شده‌اند نیز نشان داد. ما از جدول نتایج مشروط به آستانه استفاده خواهیم کرد تا نشان دهیم این وضعیت چگونه وقتی تست‌های کمی با مقادیر _p_ کوچک وجود دارد به نظر می‌رسد.

در قطعهٔ کد زیر، با استفاده از تابع _quantile_ بین ایجاد می‌کنیم، ژن‌ها را بر اساس base mean با _cut_ دسته‌بندی می‌کنیم، سطوح باین‌ها را با استفاده از نقطهٔ میانی نام‌گذاری مجدد می‌کنیم، نسبت مقادیر _p_ کمتر از 0.05 را برای هر باین محاسبه می‌کنیم و در نهایت این نسبت‌ها را رسم می‌کنیم (شکل زیر).

```
qs <- c(0, quantile(resLFC1$baseMean[resLFC1$baseMean > 0], 0:6/6))
bins <- cut(resLFC1$baseMean, qs)
levels(bins) <- paste0("~", round(signif((qs[-1] + qs[-length(qs)])/2, 2)))
fractionSig <- tapply(resLFC1$pvalue, bins, function(p)
                          mean(p < .05, na.rm = TRUE))
barplot(fractionSig, xlab = "mean normalized count",
                     ylab = "fraction of small p values")
```

**نسبت مقادیر کوچک _p_ برای ژن‌هایی که بر اساس میانگین شمارش normalization (نرمال‌سازی) شده دسته‌بندی شده‌اند.** مقادیر _p_ حاصل از یک آزمون برای بررسی این است که log2 fold change بزرگ‌تر از 1 یا کمتر از -1 است. این نمودار نشان می‌دهد ژن‌هایی با میانگین شمارش بسیار کم قدرت آماری اندکی دارند یا عملاً هیچ قدرتی ندارند و بهتر است از آزمون حذف شوند.

در نگاه اول شاید حذف این ژن‌ها فایدهٔ کمی به‌نظر برسد؛ بالاخره آزمون آن‌ها را غیر‌معنادار تشخیص داده است. با این حال، این ژن‌ها بر روی تعدیل multiple testing (آزمون‌های چندگانه) تأثیر دارند و عملکرد این تعدیل با حذف چنین ژن‌هایی بهتر می‌شود. با حذف ژن‌های با شمارش کم از ورودی رویهٔ false discovery rate (نرخ کشف کاذب)، می‌توانیم ژن‌های بیشتری را در میان ژن‌های باقی‌مانده به‌عنوان معنادار بیابیم و در نتیجه قدرت آزمون‌مان افزایش یابد. این رویکرد به عنوان فیلترینگ مستقل شناخته می‌شود.

نرم‌افزار _DESeq2_ به‌طور خودکار فیلترینگ مستقل را انجام می‌دهد تا تعداد ژن‌هایی با مقدار p تعدیل‌شده کمتر از یک مقدار بحرانی را بیشینه کند (به‌طور پیش‌فرض `alpha` بر روی 0.1 تنظیم شده است). این فیلترینگ مستقل خودکار توسط تابع _results_ انجام می‌شود و می‌توان آن را از طریق این تابع کنترل کرد.

اصطلاح _independent_ یک نکتهٔ مهم را برجسته می‌کند. چنین فیلتری...
مجاز بودن این کار تنها زمانی برقرار است که آماری که براساس آن فیلتر انجام می‌دهیم (در اینجا میانگین normalized count (شمارش) نرمال‌شده در میان همهٔ نمونه‌ها) تحت فرض صفر مستقل از آمارهٔ آزمون واقعی (مقدار p) باشد. در غیر این صورت، فیلتر کردن آزمون را نامعتبر خواهد کرد و در نتیجه فروض روش BH نقض می‌شود. نرم‌افزار فیلترینگ مستقل که درون _DESeq2_ استفاده شده از بستهٔ _[genefilter](https://bioconductor.org/packages/3.23/genefilter)_ گرفته شده است، که مرجعی به مقاله‌ای دربارهٔ پایه‌های آماری فیلترینگ مستقل دارد (Bourgon, Gentleman, and Huber 2010).

## ۶٫۵ وزن‌دهی مستقل فرضیه‌ها

تعمیم کلی ایدهٔ فیلتر بر اساس مقدار p این است که به هر فرضیه وزن تخصیص دهیم تا توان آزمون بهینه شود. بسته‌ای در Bioconductor به نام _[IHW](https://bioconductor.org/packages/3.23/IHW)_ روش _Independent Hypothesis Weighting_ را پیاده‌سازی می‌کند (Ignatiadis et al. 2016). برای نمونهٔ استفاده از _IHW_ در کنار _DESeq2_ به ویگنت بستهٔ _DESeq2_ مراجعه کنید. به‌ویژه، قطعه‌کد زیر (که در اینجا اجرا نشده است) را می‌توان به‌جای فیلترینگ مستقل شرح‌داده‌شدهٔ بالا برای اجرای IHW به‌کار برد.

```
library("IHW")
res.ihw <- results(dds, filterFun=ihw)
```

# 7 حاشیه‌نویسی و صدور نتایج

جدول نتایج ما تا کنون تنها شامل شناسه‌های Ensembl gene (ژن) است، اما نام‌های جایگزین ژن ممکن است در تفسیر اطلاعات مفیدتر باشند. بسته‌های حاشیه‌نویسی در Bioconductor در نگاشتن طرح‌های مختلف شناسه به یکدیگر کمک می‌کنند. بستهٔ _[AnnotationDbi](https://bioconductor.org/packages/3.23/AnnotationDbi)_ و بستهٔ حاشیه‌نویسی _[org.Hs.eg.db](https://bioconductor.org/packages/3.23/org.Hs.eg.db)_ را بارگذاری می‌کنیم:

```
library("AnnotationDbi")
library("org.Hs.eg.db")
```

این بستهٔ حاشیه‌نویسیِ ارگانیسم (“org”) برای _Homo sapiens_ (“Hs”) است که به‌صورت یک بستهٔ پایگاه‌دادهٔ _AnnotationDbi_ (“db”) سازمان‌دهی شده و از Entrez Gene IDs (“eg”) به‌عنوان کلید اولیه استفاده می‌کند. برای گرفتن فهرستی از همهٔ نوع‌های کلید موجود، از دستور زیر استفاده کنید:

```
columns(org.Hs.eg.db)
```

```
##  [1] "ACCNUM"       "ALIAS"        "ENSEMBL"      "ENSEMBLPROT"  "ENSEMBLTRANS"
##  [6] "ENTREZID"     "ENZYME"       "EVIDENCE"     "EVIDENCEALL"  "GENENAME"    
## [11] "GENETYPE"     "GO"           "GOALL"        "IPI"          "MAP"         
## [16] "OMIM"         "ONTOLOGY"     "ONTOLOGYALL"  "PATH"         "PFAM"        
## [21] "PMID"         "PROSITE"      "REFSEQ"       "SYMBOL"       "UCSCKG"      
## [26] "UNIPROT"
```

می‌توانیم از تابع _mapIds_ برای افزودن ستون‌های جداگانه به جدول نتایج استفاده کنیم. نام ردیف‌های جدول نتایج را به‌عنوان کلید می‌دهیم، و مشخص می‌کنیم که `keytype=ENSEMBL` . آرگومان `column` به تابع _mapIds_ می‌گوید که چه اطلاعاتی را می‌خواهیم، و آرگومان `multiVals` تعیین می‌کند در صورت وجود چند مقدار مختلف برای یک مقدار ورودی چه باید کرد. در اینجا می‌خواهیم فقط اولین مقدار موجود در پایگاه‌داده بازگردانده شود. برای افزودن نماد ژن و شناسهٔ Entrez، دوبار _mapIds_ را فراخوانی می‌کنیم.

```
ens.str <- substr(rownames(res), 1, 15)
res$symbol <- mapIds(org.Hs.eg.db,
                     keys=ens.str,
                     column="SYMBOL",
                     keytype="ENSEMBL",
                     multiVals="first")
res$entrez <- mapIds(org.Hs.eg.db,
                     keys=ens.str,
                     column="ENTREZID",
                     keytype="ENSEMBL",
                     multiVals="first")
```

اکنون نتایج شامل شناسه‌های خارجی ژن موردنظر است:

```
resOrdered <- res[order(res$pvalue),]
head(resOrdered)
```

```
## log2 fold change (MAP): dex trt vs untrt 
## Wald test p-value: dex trt vs untrt 
## DataFrame with 6 rows and 7 columns
##                     baseMean log2FoldChange     lfcSE       pvalue         padj
##                    <numeric>      <numeric> <numeric>    <numeric>    <numeric>
## ENSG00000189221.9   2371.265        3.38410  0.136340 2.47518e-138 3.95806e-134
## ENSG00000120129.5   3417.255        2.95871  0.121485 3.44226e-133 2.75226e-129
## ENSG00000101347.9  14106.720        3.73919  0.157542 1.66892e-127 8.89591e-124
## ENSG00000152583.12   973.479        4.48318  0.199191 2.26145e-115 9.04071e-112
## ENSG00000196136.17  2708.309        3.22904  0.144707 1.23286e-112 3.94293e-109
## ENSG00000211445.11 12502.886        3.75413  0.170078 2.52549e-111 6.73085e-108
##                         symbol      entrez
##                    <character> <character>
## ENSG00000189221.9         MAOA        4128
## ENSG00000120129.5        DUSP1        1843
## ENSG00000101347.9       SAMHD1       25939
## ENSG00000152583.12     SPARCL1        8404
## ENSG00000196136.17    SERPINA3          12
## ENSG00000211445.11        GPX3        2878
```

## ۷٫۱ خروجی‌گیری از نتایج

شما می‌توانید به‌سادگی جدول نتایج را در یک فایل CSV ذخیره کنید و سپس آن را به‌اشتراک بگذارید یا با یک برنامهٔ صفحه‌گسترده مانند Excel باز کنید. فراخوانی _as.data.frame_ لازم است تا شیء _DataFrame_ (بستهٔ _[IRanges](https://bioconductor.org/packages/3.23/IRanges)_) به یک شیء _data.frame_ تبدیل شود که _write.csv_ بتواند آن را پردازش کند. در این‌جا برای نمایش فقط 100 ژن برتر را برمی‌داریم.

```
resOrderedDF <- as.data.frame(resOrdered)[1:100, ]
write.csv(resOrderedDF, file = "results.csv")
```

روش‌های پیچیده‌تر برای صدور نتایج در ویگنت _DESeq2_ شرح داده شده‌اند، که لینک‌هایی به سایر بسته‌های Bioconductor فراهم می‌کنند که تسهیل‌کنندهٔ مصورسازی و ساخت گزارش هستند.

## ۷٫۲ ترسیم تغییرات نسبت در فضای ژنومی

اگر از تابع _tximeta_ برای خواندن داده‌های کمی‌سازی استفاده کرده باشیم، آنگاه شیء _DESeqDataSet_ ما روی مجموعه‌ای از اشیاء آمادهٔ Bioconductor ساخته شده است که مختصات ژن‌ها را مشخص می‌کنند. بنابراین به‌راحتی می‌توانیم نتایج differential expression analysis (تحلیل بیان تفاضلی) را در فضای ژنومی رسم کنیم. در حالی که توابع _results_ یا _lfcShrink_ به‌صورت پیش‌فرض یک _DataFrame_ بازمی‌گردانند، با استفاده از آرگومان `format` می‌توانیم خروجی از نوع _GRanges_ یا _GRangesList_ درخواست کنیم (نوع دوم تنها در صورتی ممکن است که پیش از ایجاد _DESeqDataSet_ از تابع _addExons_ در بستهٔ _tximeta_ استفاده کرده باشیم).

```
resGR <- lfcShrink(dds, coef="dex_trt_vs_untrt", type="apeglm", format="GRanges")
resGR
```

```
## GRanges object with 16637 ranges and 5 metadata columns:
##                      seqnames              ranges strand |  baseMean
##                         <Rle>           <IRanges>  <Rle> | <numeric>
##   ENSG00000000003.14     chrX 100627109-100639991      - |  740.1093
##   ENSG00000000419.12    chr20   50934867-50958555      - |  511.6990
##   ENSG00000000457.13     chr1 169849631-169894267      - |  314.1680
##   ENSG00000000460.16     chr1 169662007-169854080      + |   79.7988
##   ENSG00000000971.15     chr1 196651878-196747504      + | 5715.3064
##                  ...      ...                 ...    ... .       ...
##    ENSG00000285953.1     chr7   92131774-92245924      - |   29.5747
##    ENSG00000285967.1     chr5   36864425-36876700      - |  181.1650
##    ENSG00000285976.1     chr6   63572012-63583587      + |  875.4424
##    ENSG00000285979.1    chr16   57177349-57181390      + |   38.3502
##    ENSG00000285991.1     chr6 149817937-149896011      - |   11.2772
##                      log2FoldChange     lfcSE      pvalue        padj
##                           <numeric> <numeric>   <numeric>   <numeric>
##   ENSG00000000003.14     -0.3401220 0.1063304 6.65282e-04 4.63552e-03
##   ENSG00000000419.12      0.1770178 0.1218213 1.13720e-01 2.88125e-01
##   ENSG00000000457.13      0.0269533 0.1394669 8.27650e-01 9.21718e-01
##   ENSG00000000460.16     -0.0616870 0.2231260 6.92964e-01 8.48743e-01
##   ENSG00000000971.15      0.4206549 0.0903614 9.59508e-07 1.36387e-05
##                  ...            ...       ...         ...         ...
##    ENSG00000285953.1     -1.2313653  0.916996  0.00311401   0.0171889
##    ENSG00000285967.1     -0.2623422  0.169901  0.06919688   0.2019448
##    ENSG00000285976.1      0.2247352  0.136898  0.06675037   0.1965808
##    ENSG00000285979.1      0.1614980  0.257628  0.33148631   0.5713913
##    ENSG00000285991.1     -0.0168702  0.290081  0.87313221          NA
##   -------
##   seqinfo: 25 sequences (1 circular) from hg38 genome
```

برای برچسب‌زنی ژن‌ها روی نمودار لازم است دوباره نماد را اضافه کنیم:

```
ens.str <- substr(names(resGR), 1, 15)
resGR$symbol <- mapIds(org.Hs.eg.db, ens.str, "SYMBOL", "ENSEMBL")
```

برای رسمِ GRanges و متادیتای مرتبط — یعنی تغییرات لگاریتمیِ ضریب که ناشی از درمان با دگزامتازون هستند — از بستهٔ _[Gviz](https://bioconductor.org/packages/3.23/Gviz)_ استفاده می‌کنیم.

```
library("Gviz")
```

قطعه‌کد زیر بازه‌ای به طول 1٬000٬000 جفت باز بالادست و پایین‌دست را نسبت به ژنی که کمترین مقدار p را دارد مشخص می‌کند. برای ژن‌های واقع در این پنجره زیرمجموعه‌ای از نتایج کامل ایجاد می‌کنیم. اگر نماد وجود داشته باشد و در زیرمجموعه تک‌رُدی باشد، آن را به‌عنوان نام اضافه می‌کنیم.

```
window <- resGR[topGene] + 1e6
strand(window) <- "*"
resGRsub <- resGR[resGR %over% window]
naOrDup <- is.na(resGRsub$symbol) | duplicated(resGRsub$symbol)
resGRsub$group <- ifelse(naOrDup, names(resGRsub), resGRsub$symbol)
```

برداری ایجاد می‌کنیم که مشخص کند آیا ژن‌های این زیرمجموعه مقدار کمی از `padj` داشته‌اند یا خیر.

```
status <- factor(ifelse(resGRsub$padj < 0.05 & !is.na(resGRsub$padj),
                        "sig", "notsig"))
```

سپس می‌توانیم نتایج را با توابع _[Gviz](https://bioconductor.org/packages/3.23/Gviz)_ رسم کنیم (شکل زیر). یک «ردیف محور» برای مشخص کردن موقعیت در ژنوم می‌سازیم، یک ردیف که ژن‌ها و نام‌هایشان را نشان می‌دهد و بر اساس معنی‌داری رنگ‌آمیزی می‌شود، و یک ردیف داده که میله‌های عمودی را رسم می‌کند که تغییرات لگاریتمیِ تعدیلات‌شدهٔ ضریب تولیدشده توسط _DESeq2_ را نشان می‌دهد؛ این مقادیر تنها زمانی بزرگ هستند که اثر به‌خوبی توسط اطلاعات موجود در شمارش‌ها پشتیبانی شده باشد.

```
options(ucscChromosomeNames = FALSE)
g <- GenomeAxisTrack()
a <- AnnotationTrack(resGRsub, name = "gene ranges", feature = status)
d <- DataTrack(resGRsub, data = "log2FoldChange", baseline = 0,
               type = "h", name = "log2 fold change", strand = "+")
plotTracks(list(g, d, a), groupAnnotation = "group",
           notsig = "grey", sig = "hotpink")
```

**log2 fold changes in genomic region surrounding the gene with smallest adjusted _p_ value.** ژن‌هایی که به رنگ صورتی مشخص شده‌اند مقدار adjusted p-value (مقدار p تعدیل‌شده) کمتر از 0.1 دارند.

# 8 حذف آثار دسته‌ای پنهان

فرض کنید ما نمی‌دانستیم در آزمایش از خطوط سلولی مختلف استفاده شده است و تنها اطلاع ما اعمال درمان با دگزامتازون بود. اثر خط سلولی بر شمارش‌ها در این صورت نمایانگر یک تغییر ناخواسته و پنهان خواهد بود که ممکن است بسیاری یا همهٔ ژن‌ها را در مجموعه‌داده تحت تاثیر قرار دهد. می‌توانیم از روش‌های آماری طراحی‌شده برای RNA-seq در بستهٔ _[sva](https://bioconductor.org/packages/3.23/sva)_ (Leek 2014) یا بستهٔ _[RUVSeq](https://bioconductor.org/packages/3.23/RUVSeq)_ (Risso et al. 2014) در Bioconductor برای کشف چنین گروه‌بندی‌هایی از نمونه‌ها استفاده کنیم، و سپس آن‌ها را به طرح _DESeqDataSet_ اضافه کنیم تا اثرشان را کنترل کنیم.

بستهٔ _SVA_ از اصطلاح متغیرهای جانشین برای متغیرهای برآوردشده‌ای استفاده می‌کند که می‌خواهیم در تحلیل لحاظ شوند، در حالی که بستهٔ RUV از اصطلاح عوامل تغییر ناخواسته استفاده می‌کند و خودِ نام بسته «Remove Unwanted Variation» این عنوان را توضیح می‌دهد. ابتدا از _SVA_ برای یافتن آثار دسته‌ای پنهان استفاده می‌کنیم و سپس به سراغ _RUV_ می‌رویم.

## ۸٫۱ استفاده از SVA همراه با DESeq2

```
library("sva")
```

در ادامه ماتریسی از normalized count (شمارش)‌های نرمال‌شده را به‌دست می‌آوریم که در آن میانگین شمارش در میان نمونه‌ها بزرگ‌تر از 1 است. همان‌طور که پیش‌تر توضیح دادیم، هدف بازیابی هرگونه اثر دسته‌ای پنهان است، در حالتی که اطلاعات مربوط به خط سلولی را نداریم. بنابراین از ماتریس مدل کامل با متغیر _dex_ استفاده می‌کنیم و یک ماتریس مدل کاهش‌یافته یا تهی که تنها شامل ترم ثابت است می‌سازیم. در پایان مشخص می‌کنیم که می‌خواهیم 2 متغیر جانشین برآورد شود. برای اطلاعات بیشتر صفحهٔ راهنمای تابع _svaseq_ را با وارد کردن `?svaseq` مطالعه کنید.

```
dat  <- counts(dds, normalized = TRUE)
idx  <- rowMeans(dat) > 1
dat  <- dat[idx, ]
mod  <- model.matrix(~ dex, colData(dds))
mod0 <- model.matrix(~   1, colData(dds))
svseq <- svaseq(dat, mod, mod0, n.sv = 2)
```

```
## Number of significant surrogate variables is:  2 
## Iteration (out of 5 ):1  2  3  4  5
```

```
svseq$sv
```

```
##            [,1]        [,2]
## [1,]  0.2096171 -0.37402683
## [2,]  0.2139238 -0.38481048
## [3,]  0.1486319 -0.19478674
## [4,]  0.1314682 -0.24741213
## [5,]  0.2553053  0.53388836
## [6,]  0.2569562  0.56828275
## [7,] -0.6238462  0.05013275
## [8,] -0.5920563  0.04873233
```
از آن‌جا که در واقع خطوط سلولی را می‌شناسیم، می‌توانیم ببینیم روش SVA تا چه حد در بازسازی این متغیرها موفق بوده است (شکل زیر).

```
par(mfrow = c(2, 1), mar = c(3,5,3,1))
for (i in 1:2) {
  stripchart(svseq$sv[, i] ~ dds$cell, vertical = TRUE, main = paste0("SV", i))
  abline(h = 0)
 }
```

**متغیرهای جانشین ۱ و ۲ بر حسب خط سلولی رسم شده‌اند.** در اینجا منبع پنهان تغییرپذیری (خط سلولی) را می‌دانیم و بنابراین می‌توانیم مشاهده کنیم که رویهٔ SVA چگونه یک منبع تغییر را که با خط سلولی همبسته است شناسایی می‌کند.

در انتها، برای استفاده از SVA به‌منظور حذف هر تأثیری که متغیرهای جانشین ممکن است روی count (شمارش)ها داشته باشند، کافی است این دو متغیر جانشین را به‌صورت ستون به _DESeqDataSet_ اضافه کنیم و سپس آن‌ها را در طراحی وارد کنیم:

```
ddssva <- dds
ddssva$SV1 <- svseq$sv[,1]
ddssva$SV2 <- svseq$sv[,2]
design(ddssva) <- ~ SV1 + SV2 + dex
```

سپس می‌توانیم با اجرای _DESeq_ با طراحی جدید، نتایجی را به‌دست آوریم که برای متغیرهای جانشین کنترل‌شده باشند.

## ۸٫۲ استفاده از RUV همراه با DESeq2

همچنین می‌توانیم از روش _RUV_ در بستهٔ _RUVSeq_ برای شناسایی batch effect (اثر دسته‌ای)های پنهان استفاده کنیم.

```
library("RUVSeq")
```

می‌توانیم از تابع `RUVg` برای برآورد عوامل تغییرات ناخواسته استفاده کنیم؛ این عوامل مشابهِ surrogate variables در _SVA_ هستند. تفاوت نسبت به روش _SVA_ که پیش‌تر نشان داده شد این است که ابتدا _DESeq_ و _results_ را اجرا می‌کنیم تا p‑valueهایی برای تحلیل بدون اطلاع از دسته‌ها به‌دست آوریم، مثلاً فقط `~ dex`. فرض کنید جدول نتایج حاصل `res` باشد؛ سپس مجموعه‌ای از ژن‌های کنترل تجربی را با انتخاب gene (ژن)‌هایی که p‑value کوچک ندارند، استخراج می‌کنیم.

```
set <- newSeqExpressionSet(counts(dds))
idx  <- rowSums(counts(set) > 5) >= 2
set  <- set[idx, ]
set <- betweenLaneNormalization(set, which="upper")
not.sig <- rownames(res)[which(res$pvalue > .1)]
empirical <- rownames(set)[ rownames(set) %in% not.sig ]
set <- RUVg(set, empirical, k=2)
pData(set)
```

```
##                    W_1           W_2
## SRR1039508 -0.26933276  0.4109938600
## SRR1039509 -0.28309027  0.5195974173
## SRR1039512  0.01260963  0.0211629252
## SRR1039513 -0.14401331  0.0865517386
## SRR1039516  0.58465966  0.0131477643
## SRR1039517  0.59835009  0.0001659118
## SRR1039520 -0.21813265 -0.5302085106
## SRR1039521 -0.28105040 -0.5214111067
```

می‌توانیم عوامل برآوردشده توسط _RUV_ را رسم کنیم:

```
par(mfrow = c(2, 1), mar = c(3,5,3,1))
for (i in 1:2) {
  stripchart(pData(set)[, i] ~ dds$cell, vertical = TRUE, main = paste0("W", i))
  abline(h = 0)
 }
```

**عوامل تغییرات ناخواسته بر حسب خط سلولی رسم شده‌اند.**

همان‌طور که پیش‌تر، اگر بخواهیم برای این عوامل کنترل قائل شویم، آن‌ها را به _DESeqDataSet_ و به طراحی اضافه می‌کنیم:

```
ddsruv <- dds
ddsruv$W1 <- set$W_1
ddsruv$W2 <- set$W_2
design(ddsruv) <- ~ W1 + W2 + dex
```

سپس _DESeq_ را با طراحی جدید اجرا می‌کنیم تا پارامترها و نتایج دوباره برآورد شوند.

# ۹ آزمایش‌های time course (دورهٔ زمانی)

_DESeq2_ می‌تواند برای تحلیل تجربیات زمانی به‌کار رود؛ برای نمونه برای یافتن ژن‌هایی که در یک شرط خاص در طول زمان واکنش نشان می‌دهند در مقایسه با مجموعه‌ای از نمونه‌های پایه.

در اینجا یک تحلیل پایه‌ای سری زمانی را با بستهٔ دادهٔ _[fission](https://bioconductor.org/packages/3.23/fission)_ نشان می‌دهیم که شامل شمارش‌های ژن برای یک سری زمانی RNA-seq از مخمر تقسیم‌شونده است (Leong et al. 2014). مخمرها در معرض استرس اکسایشی قرار گرفتند و نیمی از نمونه‌ها حذف ژن _atf21_ را داشتند. از فرمول طراحی‌ای استفاده می‌کنیم که اختلاف سویه در زمان 0، تغییرات در طول زمان، و هر اختلاف اختصاصی سویه در طول زمان را مدل می‌کند (ترم تداخل `strain:minute`).

```
library("fission")
data("fission")
ddsTC <- DESeqDataSet(fission, ~ strain + minute + strain:minute)
```

بخش کد زیر یک آزمون نسبت درست‌نمایی را اجرا می‌کند که در آن اختلافات اختصاصی سویه در طول زمان حذف می‌شوند. ژن‌هایی که از این آزمون p‑valueهای کوچکی می‌گیرند، آن‌هایی هستند که در یک یا چند نقطهٔ زمانی پس از زمان صفر اثر اختصاصی سویه نشان داده‌اند. بنابراین توجه داشته باشید که ژن‌هایی که در هر دو سویه به‌طور مشابه در طول زمان افزایش یا کاهش یافته‌اند، p‑valueهای کوچکی نخواهند داشت.

```
ddsTC <- DESeq(ddsTC, test="LRT", reduced = ~ strain + minute)
resTC <- results(ddsTC)
resTC$symbol <- mcols(ddsTC)$symbol
head(resTC[order(resTC$padj),], 4)
```

```
## log2 fold change (MLE): strainmut.minute180 
## LRT p-value: '~ strain + minute + strain:minute' vs '~ strain + minute' 
## DataFrame with 4 rows and 7 columns
##               baseMean log2FoldChange     lfcSE      stat      pvalue
##              <numeric>      <numeric> <numeric> <numeric>   <numeric>
## SPBC2F12.09c   174.671     -2.6567195  0.752261   97.2834 1.97415e-19
## SPAC1002.18    444.505     -0.0509321  0.204299   56.9536 5.16955e-11
## SPAC1002.19    336.373     -0.3927490  0.573494   43.5339 2.87980e-08
## SPAC1002.17c   261.773     -1.1387648  0.606129   39.3158 2.05137e-07
##                     padj      symbol
##                <numeric> <character>
## SPBC2F12.09c 1.33453e-15       atf21
## SPAC1002.18  1.74731e-07        urg3
## SPAC1002.19  6.48916e-05        urg1
## SPAC1002.17c 3.46682e-04        urg2
```

این تنها یکی از آزمون‌هایی است که می‌توان به داده‌های سری زمانی اعمال کرد. گزینهٔ دیگر مدل‌سازی شمارش‌ها به‌عنوان یک تابع پیوستهٔ زمان و افزودن یک ترم تداخل بین شرط و آن تابع پیوسته است. می‌توان چنین مدلی را با توابع پایهٔ اسپلاین در R ساخت؛ رویکردی جدیدتر استفاده از فرآیندهای گاوسی است (Tonner et al. 2017).

می‌توانیم شمارش‌ها را برای گروه‌ها در طول زمان با استفاده از _[ggplot2](https://cran.r-project.org/package=ggplot2)_ رسم کنیم؛ برای ژنی که کوچک‌ترین adjusted p-value (مقدار p تعدیل‌شده) را دارد — آزمون برای پروفایل زمانی وابسته به شرط و با در نظر گرفتن اختلافات در زمان 0 (شکل زیر). به‌خاطر داشته باشید که ترم‌های تداخل، اختلاف بین دو گروه در زمان مشخص پس از در نظر گرفتن اختلاف زمان 0 هستند.

```
fiss <- plotCounts(ddsTC, which.min(resTC$padj), 
                   intgroup = c("minute","strain"), returnData = TRUE)
fiss$minute <- as.numeric(as.character(fiss$minute))
ggplot(fiss,
  aes(x = minute, y = count, color = strain, group = strain)) + 
  geom_point() + stat_summary(fun.y=mean, geom="line") +
  scale_y_log10()
```

**شمارش‌های نرمال‌شده — نتیجهٔ normalization (نرمال‌سازی) — برای ژنی با تغییرات وابسته به شرط در طول زمان.**

آزمون‌های والد برای تغییرات چندبرابریِ لگاریتمی به پایهٔ 2 در نقاط زمانی منفرد را می‌توان با استفاده از آرگومان `test` در _results_ بررسی کرد:

```
resultsNames(ddsTC)
```

```
##  [1] "Intercept"           "strain_mut_vs_wt"    "minute_15_vs_0"     
##  [4] "minute_30_vs_0"      "minute_60_vs_0"      "minute_120_vs_0"    
##  [7] "minute_180_vs_0"     "strainmut.minute15"  "strainmut.minute30" 
## [10] "strainmut.minute60"  "strainmut.minute120" "strainmut.minute180"
```

```
res30 <- results(ddsTC, name="strainmut.minute30", test="Wald")
res30[which.min(res30$padj),]
```

```
## log2 fold change (MLE): strainmut.minute30 
## Wald test p-value: strainmut.minute30 
## DataFrame with 1 row and 6 columns
##               baseMean log2FoldChange     lfcSE      stat      pvalue      padj
##              <numeric>      <numeric> <numeric> <numeric>   <numeric> <numeric>
## SPBC2F12.09c   174.671       -2.60047  0.634343  -4.09947 4.14099e-05  0.279931
```

هم‌چنین می‌توان ژن‌های معنادار را بر اساس پروفایل‌های زمانی آن‌ها خوشه‌بندی کرد. ماتریسی از تغییرات چندبرابریِ لگاریتمی به پایهٔ 2 را با استفاده از تابع _coef_ استخراج می‌کنیم. توجه داشته باشید که این‌ها برآوردهای بیشینهٔ درست‌نمایی هستند. برای به‌دست‌آوردن LFCهای جمع‌شده (shrunken)، باید آن‌ها را یک ضریب در هر نوبت با استفاده از `lfcShrink` استخراج کرد.

```
betas <- coef(ddsTC)
colnames(betas)
```

```
##  [1] "Intercept"           "strain_mut_vs_wt"    "minute_15_vs_0"     
##  [4] "minute_30_vs_0"      "minute_60_vs_0"      "minute_120_vs_0"    
##  [7] "minute_180_vs_0"     "strainmut.minute15"  "strainmut.minute30" 
## [10] "strainmut.minute60"  "strainmut.minute120" "strainmut.minute180"
```

اکنون می‌توانیم تغییرات لگاریتمیِ پایهٔ 2 را در یک نقشهٔ حرارتی رسم کنیم (شکل زیر).

```
topGenes <- head(order(resTC$padj),20)
mat <- betas[topGenes, -c(1,2)]
thr <- 3 
mat[mat < -thr] <- -thr
mat[mat > thr] <- thr
pheatmap(mat, breaks=seq(from=-thr, to=thr, length=101),
         cluster_col=FALSE)
```

**نقشهٔ حرارتیِ تغییرات لگاریتمیِ پایهٔ 2 برای ژن‌هایی با کوچک‌ترین مقدار p تعدیل‌شده.** مجموعهٔ پایینِ ژن‌ها نشان‌دهندهٔ القای قوی بیان برای نمونه‌های پایه در دقایق ۱۵–۶۰ است (کادرهای قرمز در گوشهٔ پایین چپ)، ولی سپس اختلافات جزئی‌ای برای سویهٔ موتانت در مقاطع بعدی دیده می‌شود (نمایش در کادرهای گوشهٔ پایین راست).

# ۱۰ پیوست

## ۱۰٫۱ جزئیات به‌روز دربارهٔ کمی‌سازی

روند کاری فوق، مراحل برآورد فراوانی را که منجر به ایجاد اشیاء `gse` و `se` در بستهٔ _airway_ شد، تشریح می‌کند. این شامل نگاشت read (خوانش)های RNA-seq به رونوشت (transcript)‌های مرجع انسانی در GENCODE v29 با استفاده از salmon v0.14.1 بود. این گام برآورد فراوانی در سال 2019 انجام شد.

برای ارائهٔ جزئیات به‌روزتر دربارهٔ برآورد فراوانی، اطلاعات زیر را در پیوست قرار می‌دهیم. جزئیات به‌روز دربارهٔ برآورد فراوانی توسط Vince Carey در 2026 تهیه شده و از ابزارهای جدید و همچنین GENCODE v49 استفاده می‌کند.

### ۱۰٫۱٫۱ دانلود فایل‌های FASTQ

روش‌های پیشنهادی برای دسترسی به داده‌های خام جهت پیش‌پردازش و تحلیل در طول زمان تغییر می‌کنند. از تاریخ 13 آوریل 2026، NCBI `fasterq-dump` را برای عملیات شبکهٔ با کارایی بالا که منابع را از Sequence Read Archive بازیابی می‌کنند فراهم می‌کند. [SRA-tools wiki](https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump) `prefetch` و `fasterq-dump` را شرح می‌دهد. یکی از رویکردها برای دریافت فایل‌های FASTQ آزمایش airway استفادهٔ مستقیم از `fasterq-dump` است. دستورات زیر برای یک نمونه FASTQ فشرده‌شده با gzip تولید می‌کنند:

```
fasterq-dump -p -e 4 SRR1039509
gzip SRR1039509_1.fastq
gzip SRR1039509_2.fastq
```

پس از اجرای این روند برای ۸ نمونهٔ آزمایش airway، تقریباً ۲۲ گیگابایت FASTQ فشرده موجود خواهد بود.

### ۱۰٫۱٫۲ ساخت نمایهٔ Salmon

ما از

```
salmon index -t gencode.v49.transcripts.fa.gz -i gencode.v49_salmon_1.11.4
```

پس از بازیابی FASTA فشرده از [GENCODE](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.transcripts.fa.gz) استفاده کردیم.

فرآیند ایندکس‌سازی پیام‌های زیادی تولید می‌کند. برخی نمونه‌ها:

```
[2026-04-13 06:23:04.280] [puff::index::jointLog] [warning] Entry with header [ENST00000631435.1|ENSG00000282253.1|OTTHUMG00000190586.2|OTTHUMT00000485282.2|TRBD1-201|TRBD1|12|TR_D_gene|], had length less than equal to the k-mer length of 31 (perhaps after poly-A clipping)

[2026-04-13 06:23:04.314] [puff::index::jointLog] [warning] Removed 16702 transcripts that were sequence duplicates of indexed transcripts.
[2026-04-13 06:23:04.314] [puff::index::jointLog] [warning] If you wish to retain duplicate transcripts, please use the `--keepDuplicates` flag
[2026-04-13 06:23:04.320] [puff::index::jointLog] [info] Replaced 100014 non-ATCG nucleotides
[2026-04-13 06:23:04.320] [puff::index::jointLog] [info] Clipped poly-A tails from 9880 transcripts
wrote 516988 cleaned references
[2026-04-13 06:23:05.600] [puff::index::jointLog] [info] Filter size not provided; estimating from number of distinct k-mers 
[2026-04-13 06:23:12.270] [puff::index::jointLog] [info] ntHll estimated 185456630 distinct k-mers, setting filter size to 2^32
```

پوشهٔ حاصل دارای محتوایی به‌صورت زیر است:

```
gencode.v49_salmon_1.11.4
├── complete_ref_lens.bin
├── ctable.bin
├── ctg_offsets.bin
├── duplicate_clusters.tsv
├── info.json
├── pre_indexing.log
├── ref_indexing.log
├── refAccumLengths.bin
├── reflengths.bin
├── refseq.bin
├── sshash.bin
└── versionInfo.json
```

### ۱۰٫۱٫۳ کمی‌سازی abundance (فراوانی) با Salmon

فرمان snakemake با گزینهٔ `-j 4` روی یک M4 macbook air با 32 GB حافظهٔ رم اجرا شد و در مدت یک ساعت تکمیل شد.

پوشهٔ تولیدشده برای یک نمونه ساختاری به‌شکل زیر دارد:

```
quants
├── SRR1039508
│   ├── aux_info
│   │   ├── ambig_info.tsv
│   │   ├── bootstrap
│   │   │   ├── bootstraps.gz
│   │   │   └── names.tsv.gz
│   │   ├── exp_gc.gz
│   │   ├── expected_bias.gz
│   │   ├── fld.gz
│   │   ├── meta_info.json
│   │   ├── obs_gc.gz
│   │   ├── observed_bias_3p.gz
│   │   └── observed_bias.gz
│   ├── cmd_info.json
│   ├── lib_format_counts.json
│   ├── libParams
│   │   └── flenDist.txt
│   ├── logs
│   │   └── salmon_quant.log
│   └── quant.sf
```

مجموع فضای دیسک برای برآوردهای فراوانیِ ۸ نمونه تقریباً ۸ گیگابایت بود.

### ۱۰٫۱٫۴ تولید RangedSummarizedExperiment با tximeta

با Gencode v49، `tximeta` روی برآوردهای فراوانی اعمال شد.
برای ۸ نمونه پیام‌هایی تولید می‌شود که شامل موارد زیر است:

```
building TxDb with 'txdbmaker' package
Import genomic features from the file as a GRanges object ... trying URL 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.annotation.gtf.gz'
Content type 'unknown' length 93374019 bytes (89.0 MB)
==================================================
OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
generating transcript ranges
fetching genome info for GENCODE
Warning messages:
1: In .get_cds_IDX(mcols0$type, mcols0$phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
2: In .makeTxDb_normarg_chrominfo(chrominfo) :
  genome version information is not available for this TxDb object
3: In checkAssays2Txps(assays, txps) : 

Warning: the annotation is missing some transcripts that were quantified.
11097 out of 517038 txps were missing from GTF/GFF but were in the indexed FASTA
(e.g. this can occur with transcripts located on haplotype chromosomes).
In order to build a ranged SummarizedExperiment, these txps were removed.
To keep these txps, and to skip adding ranges, use skipMeta=TRUE

Example missing txps: [ENST00000707233.1, ENST00000710274.1, ENST00000707308.1, ...]
```

بسته به وضعیت اتصال شما به اینترنت، برخی از پرس‌وجوهای FTP که `tximeta` از طرف کاربر انجام می‌دهد ممکن است شکست بخورند. به خطاهای 421 «سرویس در دسترس نیست» توجه کنید، و در صورت مشاهده، پس از بهبود اتصال مجدداً تلاش کنید.

# 11 اطلاعات نشست

در بخش پایانی این سند، تابع _sessionInfo_ را فراخوانی می‌کنیم که شمارهٔ نسخهٔ R و نسخه‌های تمام بسته‌های به‌کاررفته در این نشست را گزارش می‌دهد. نگهداری چنین گزارشی عادت خوبی است، زیرا در صورت توقف اجرای یک اسکریپت R یا تغییر نتایج به‌دلیل به‌روزرسانی توابع در نسخه‌های جدید بسته‌ها، کمک می‌کند تا منشأ مشکل را شناسایی کنید. با قرار دادن این گزارش در انتهای اسکریپت، گزارش‌های شما قابل بازتولیدتر خواهند شد.

اطلاعات نشست باید همیشه همراه با تمام کدهای به‌کاررفته در تحلیل، در هر ایمیلی که به https://support.bioconductor.org/ ارسال می‌شود نیز ضمیمه گردد.

```
sessionInfo()
```

```
## R version 4.6.0 RC (2026-04-17 r89917)
## Platform: x86_64-pc-linux-gnu
## Running under: Ubuntu 24.04.4 LTS
## 
## Matrix products: default
## BLAS:   /home/biocbuild/bbs-3.23-bioc/R/lib/libRblas.so 
## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.12.0  LAPACK version 3.12.0
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_GB              LC_COLLATE=C              
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## time zone: America/New_York
## tzcode source: system (glibc)
## 
## attached base packages:
## [1] grid      stats4    stats     graphics  grDevices utils     datasets 
## [8] methods   base     
## 
## other attached packages:
##  [1] fission_1.32.0              RUVSeq_1.46.0              
##  [3] edgeR_4.10.1                limma_3.68.4               
##  [5] EDASeq_2.46.0               ShortRead_1.70.0           
##  [7] GenomicAlignments_1.48.0    Rsamtools_2.28.0           
##  [9] Biostrings_2.80.1           XVector_0.52.0             
## [11] sva_3.60.0                  BiocParallel_1.46.0        
## [13] mgcv_1.9-4                  nlme_3.1-169               
## [15] Gviz_1.56.0                 org.Hs.eg.db_3.23.1        
## [17] genefilter_1.94.0           apeglm_1.34.0              
## [19] ggbeeswarm_0.7.3            glmpca_0.2.0               
## [21] PoiClaClu_1.0.2.1           RColorBrewer_1.1-3         
## [23] pheatmap_1.0.13             ggplot2_4.0.3              
## [25] dplyr_1.2.1                 vsn_3.80.0                 
## [27] DESeq2_1.52.0               magrittr_2.0.5             
## [29] GenomicFeatures_1.64.0      AnnotationDbi_1.74.0       
## [31] tximeta_1.30.0              airway_1.32.0              
## [33] SummarizedExperiment_1.42.0 Biobase_2.72.0             
## [35] GenomicRanges_1.64.0        Seqinfo_1.2.0              
## [37] IRanges_2.46.0              S4Vectors_0.50.1           
## [39] BiocGenerics_0.58.1         generics_0.1.4             
## [41] MatrixGenerics_1.24.0       matrixStats_1.5.0          
## [43] rmarkdown_2.31              knitr_1.51                 
## [45] BiocStyle_2.40.0           
## 
## loaded via a namespace (and not attached):
##   [1] splines_4.6.0            BiocIO_1.22.0            bitops_1.0-9            
##   [4] filelock_1.0.3           R.oo_1.27.1              tibble_3.3.1            
##   [7] preprocessCore_1.74.0    XML_3.99-0.23            rpart_4.1.27            
##  [10] lifecycle_1.0.5          httr2_1.2.2              pwalign_1.8.0           
##  [13] lattice_0.22-9           vroom_1.7.1              ensembldb_2.36.1        
##  [16] MASS_7.3-65              backports_1.5.1          Hmisc_5.2-5             
##  [19] sass_0.4.10              jquerylib_0.1.4          yaml_2.3.12             
##  [22] otel_0.2.0               DBI_1.3.0                abind_1.4-8             
##  [25] R.utils_2.13.0           purrr_1.2.2              AnnotationFilter_1.36.0 
##  [28] biovizBase_1.60.0        RCurl_1.98-1.18          nnet_7.3-20             
##  [31] VariantAnnotation_1.58.0 rappdirs_0.3.4           annotate_1.90.0         
##  [34] codetools_0.2-20         DelayedArray_0.38.2      tidyselect_1.2.1        
##  [37] UCSC.utils_1.8.0         farver_2.1.2             BiocFileCache_3.2.0     
##  [40] base64enc_0.1-6          jsonlite_2.0.0           Formula_1.2-5           
##  [43] survival_3.8-6           bbmle_1.0.25.1           tools_4.6.0             
##  [46] progress_1.2.3           Rcpp_1.1.1-1.1           glue_1.8.1              
##  [49] gridExtra_2.3            SparseArray_1.12.2       xfun_0.58               
##  [52] GenomeInfoDb_1.48.0      withr_3.0.2              numDeriv_2016.8-1.1     
##  [55] BiocManager_1.30.27      fastmap_1.2.0            latticeExtra_0.6-31     
##  [58] digest_0.6.39            R6_2.6.1                 colorspace_2.1-2        
##  [61] jpeg_0.1-11              dichromat_2.0-0.1        biomaRt_2.68.0          
##  [64] RSQLite_3.53.1           R.methodsS3_1.8.2        cigarillo_1.2.0         
##  [67] hexbin_1.28.5            data.table_1.18.4        rtracklayer_1.72.0      
##  [70] htmlwidgets_1.6.4        prettyunits_1.2.0        httr_1.4.8              
##  [73] S4Arrays_1.12.0          pkgconfig_2.0.3          gtable_0.3.6            
##  [76] blob_1.3.0               hwriter_1.3.2.1          S7_0.2.2                
##  [79] htmltools_0.5.9          bookdown_0.46            ProtGenerics_1.44.0     
##  [82] scales_1.4.0             png_0.1-9                rstudioapi_0.18.0       
##  [85] tzdb_0.5.0               rjson_0.2.23             checkmate_2.3.4         
##  [88] coda_0.19-4.1            curl_7.1.0               bdsmatrix_1.3-7         
##  [91] cachem_1.1.0             stringr_1.6.0            BiocVersion_3.23.1      
##  [94] parallel_4.6.0           vipor_0.4.7              foreign_0.8-91          
##  [97] restfulr_0.0.16          pillar_1.11.1            vctrs_0.7.3             
## [100] dbplyr_2.5.2             xtable_1.8-8             cluster_2.1.8.2         
## [103] htmlTable_2.5.0          beeswarm_0.4.0           tximport_1.40.0         
## [106] evaluate_1.0.5           readr_2.2.0              tinytex_0.59            
## [109] magick_2.9.1             mvtnorm_1.4-0            cli_3.6.6               
## [112] locfit_1.5-9.12          compiler_4.6.0           rlang_1.2.0             
## [115] crayon_1.5.3             labeling_0.4.3           aroma.light_3.42.0      
## [118] interp_1.1-6             emdbook_1.3.14           affy_1.90.0             
## [121] plyr_1.8.9               stringi_1.8.7            deldir_2.0-4            
## [124] txdbmaker_1.8.0          lazyeval_0.2.3           Matrix_1.7-5            
## [127] BSgenome_1.80.0          hms_1.1.4                bit64_4.8.2             
## [130] KEGGREST_1.52.0          statmod_1.5.2            AnnotationHub_4.2.0     
## [133] memoise_2.0.1            affyio_1.82.0            bslib_0.11.0            
## [136] bit_4.6.0
```

# منابع

Anders, Simon, and Wolfgang Huber. 2010. «differential expression analysis (تحلیل بیان تفاضلی) برای داده‌های توالی count (شمارش).» _Genome Biology_ 11 (10): R106+. <https://doi.org/10.1186/gb-2010-11-10-r106> .

Anders, Simon, Paul T. Pyl, and Wolfgang Huber. 2015. «HTSeq – یک چارچوب پایتون برای کار با داده‌های توالی‌یابی با توان بالا.» _Bioinformatics_ 31 (2): 166–69. <https://doi.org/10.1093/bioinformatics/btu638> .

Benjamini, Yoav, and Yosef Hochberg. 1995. «کنترل false discovery rate (نرخ کشف کاذب): یک روش عملی و قدرتمند برای multiple testing (آزمون‌های چندگانه).» _Journal of the Royal Statistical Society. Series B (Methodological)_ 57 (1): 289–300. <http://www.jstor.org/stable/2346101> .

Bourgon, R., R. Gentleman, and W. Huber. 2010. «فیلتر مستقل توان کشف را در آزمایش‌های پرتوان افزایش می‌دهد.» _Proceedings of the National Academy of Sciences_ 107 (21): 9546–51. <https://doi.org/10.1073/pnas.0914005107> .

Bray, Nicolas, Harold Pimentel, Pall Melsted, and Lior Pachter. 2016. «تقریب احتمالاتی نزدیک به بهینه برای کمی‌سازی RNA-Seq.» _Nature Biotechnology_ 34: 525–27. <http://dx.doi.org/10.1038/nbt.3519> .

Dudoit, Rine, Yee H. Yang, Matthew J. Callow, and Terence P. Speed. 2002. «روش‌های آماری برای شناسایی ژن‌های متفاوت بیان‌شده در آزمایش‌های cDNA microarray تکرارشده.» _Statistica Sinica_ , 111–39.

Frankish, Adam, Alexandra Bignell, Andrew Berry, Andrew Yates, Anne Parker, Bianca M Schmitt, Bronwen Aken, et al. 2018. «ژن‌شناسی مرجع GENCODE برای ژنوم‌های انسان و موش.» _Nucleic Acids Research_ 47 (D1): D766–D773.

Hardcastle, Thomas, and Krystyna Kelly. 2010. «baySeq: روش‌های بیزی تجربی برای شناسایی differential expression (تحلیل بیان تفاضلی) در داده‌های شمارش توالی.» _BMC Bioinformatics_ 11 (1): 422+. <https://doi.org/10.1186/1471-2105-11-422> .

Himes, Blanca E., Xiaofeng Jiang, Peter Wagner, Ruoxi Hu, Qiyu Wang, Barbara Klanderman, Reid M. Whitaker, et al. 2014. «پروفایل‌سازی ترنسکریپتوم RNA-Seq نشان می‌دهد CRISPLD2 ژنی پاسخ‌پذیر به گلوکوکورتیکوئید است که عملکرد سایتوکاین‌ها را در سلول‌های ماهیچهٔ صاف مجاری تنفسی تنظیم می‌کند.» _PloS One_ 9 (6). <https://doi.org/10.1371/journal.pone.0099625> .

Huber, Wolfgang, Vincent J. Carey, Robert Gentleman, Simon Anders, Marc Carlson, Benilton S. Carvalho, Hector Corrada C. Bravo, et al. 2015. «هماهنگ‌سازی تحلیل‌های ژنومی پرتوان با Bioconductor.» _Nature Methods_ 12 (2): 115–21. <https://doi.org/10.1038/nmeth.3252> .

Ignatiadis, Nikolaos, Bernd Klaus, Judith Zaugg, and Wolfgang Huber. 2016. «وزن‌دهی فرضیه‌محور داده‌محور توان کشف را در آزمون‌های چندگانه در مقیاس ژنومی افزایش می‌دهد.» _Nature Methods_ . <http://dx.doi.org/10.1038/nmeth.3885> .

Köster, Johannes, and Sven Rahmann. 2012. «Snakemake - یک سامانهٔ کاریابی بیوانفورماتیک مقیاس‌پذیر.» _Bioinformatics_ . <https://doi.org/10.1093/bioinformatics/bts480> .

Law, Charity W., Yunshun Chen, Wei Shi, and Gordon K. Smyth. 2014. «Voom: وزن‌های دقت ابزارهای مدل‌خطی را برای شمارش‌های read (خوانش) در RNA‑seq فعال می‌سازند.» _Genome Biology_ 15 (2): R29+. <https://doi.org/10.1186/gb-2014-15-2-r29> .

Lawrence, Michael, Wolfgang Huber, Hervé Pagès, Patrick Aboyoun, Marc Carlson, Robert Gentleman, Martin T. Morgan, and Vincent J. Carey. 2013. «نرم‌افزاری برای محاسبه و حاشیه‌نویسی بازه‌های ژنومی.» Edited by Andreas Prlic. _PLoS Computational Biology_ 9 (8): e1003118+. <https://doi.org/10.1371/journal.pcbi.1003118> .

Leek, Jeffrey T. 2014. «svaseq: حذف batch effect (اثر دسته‌ای) و سایر نویزهای ناخواسته از داده‌های توالی‌یابی.» _Nucleic Acids Research_ 42 (21): 000. <https://doi.org/10.1093/nar/gku864> .

Leng, N., J. A. Dawson, J. A. Thomson, V. Ruotti, A. I. Rissman, B. M. G. Smits, J. D. Haag, M. N. Gould, R. M. Stewart, and C. Kendziorski. 2013. «EBSeq: یک مدل سلسله‌مراتبی بیزی تجربی برای استنباط در آزمایش‌های RNA‑seq.» _Bioinformatics_ 29 (8): 1035–43. <https://doi.org/10.1093/bioinformatics/btt087> .

Leong, Hui S., Keren Dawson, Chris Wirth, Yaoyong Li, Yvonne Connolly, Duncan L. Smith, Caroline R. Wilkinson, and Crispin J. Miller. 2014. «یک سامانهٔ غیرکدکنندهٔ جهانی RNA سطوح پروتئینی جلبک شکافندهٔ (fission yeast) را در پاسخ به استرس تنظیم می‌کند.» _Nature Communications_ 5\. <https://doi.org/10.1038/ncomms4947> .

Li, Bo, and Colin N. Dewey. 2011. «RSEM: برآورد فراوانی (quantification) دقیق رونوشت‌ها از داده‌های RNA‑Seq با یا بدون ژنوم مرجع.» _BMC Bioinformatics_ 12: 323+. <https://doi.org/10.1186/1471-2105-12-3231> .

Liao, Y., G. K. Smyth, and W. Shi. 2014. «featureCounts: یک برنامهٔ عمومی و کارآمد برای تخصیص خوانش‌ها به ویژگی‌های ژنومی.» _Bioinformatics_ 30 (7): 923–30. <https://doi.org/10.1093/bioinformatics/btt656> .

Love, Michael I., John B. Hogenesch, and Rafael A. Irizarry. 2016. «مدل‌سازی شیب توالی قطعات RNA‑Seq خطاهای سیستماتیک در برآورد فراوانی (abundance (فراوانی)) رونوشت‌ها را کاهش می‌دهد.» _Nature Biotechnology_ 34 (12): 1287–91. <http://dx.doi.org/10.1038/nbt.3682> .

Love, Michael I., Wolfgang Huber, and Simon Anders. 2014. «برآورد تعدیل‌شدهٔ تغییرات تابی (fold change) و dispersion (پراکندگی) برای داده‌های RNA‑seq با DESeq2.» _Genome Biology_ 15 (12): 550+. <https://doi.org/10.1186/s13059-014-0550-8> .

Love, Michael I., Charlotte Soneson, Peter F. Hickey, Lisa K. Johnson, N. Tessa Pierce, Lori Shepherd, Martin Morgan, and Rob Patro. 2020. «Tximeta: جمع‌های بررسی چکسام‌های توالی مرجع برای شناسایی منشأ در RNA‑seq.» _PLOS Computational Biology_ . <https://doi.org/10.1371/journal.pcbi.1007664> .
Patro, Rob, Geet Duggal, Michael I. Love, Rafael A. Irizarry, and Carl Kingsford. 2017. «Salmon برآورد فراوانی بیان transcript (رونوشت) را به‌سرعت و با درنظر گرفتن بایاس ارائه می‌کند.» _Nature Methods_. <http://dx.doi.org/10.1038/nmeth.4197> .

Risso, Davide, John Ngai, Terence P. Speed, and Sandrine Dudoit. 2014. «normalization (نرمال‌سازی) داده‌های RNA-seq با استفاده از تحلیل عاملی روی gene (ژن)‌های کنترلی یا نمونه‌ها.» _Nature Biotechnology_ 32 (9): 896–902. <https://doi.org/10.1038/nbt.2931> .

Robert, Christelle, and Mick Watson. 2015. «خطاها در برآورد فراوانی RNA-Seq بر gene (ژن)هایی که با بیماری‌های انسانی مرتبط‌اند تأثیر می‌گذارد.» _Genome Biology_. <https://doi.org/10.1186/s13059-015-0734-x> .

Robinson, M. D., D. J. McCarthy, and G. K. Smyth. 2009. «edgeR: یک بسته Bioconductor برای differential expression analysis (تحلیل بیان تفاضلی) داده‌های دیجیتال بیان gene (ژن).» _Bioinformatics_ 26 (1): 139–40. <https://doi.org/10.1093/bioinformatics/btp616> .

Schurch, Nicholas J., Pieta Schofield, Marek Gierlinski, Christian Cole, Alexander Sherstnev, Vijender Singh, Nicola Wrobel, et al. 2016. «چه تعداد تکرار زیستی در یک آزمایش RNA-Seq لازم است و کدام ابزار برای differential expression analysis (تحلیل بیان تفاضلی) مناسب‌تر است؟» 22 (6): 839–51. <https://doi.org/10.1261/rna.053959.115> .

Soneson, Charlotte, Michael I. Love, and Mark Robinson. 2015. «Differential analyses برای RNA-seq: برآوردهای در سطح transcript (رونوشت) استنباط‌های در سطح gene (ژن) را بهبود می‌بخشند.» _F1000Research_ 4 (1521). <https://doi.org/10.12688/f1000research.7563.1> .

Srivastava, Avi, Laraib Malik, Hirak Sarkar, Mohsen Zakeri, Fatemeh Almodaresi, Charlotte Soneson, Michael I. Love, Carl Kingsford, and Rob Patro. 2020. «روش‌های تراز و نگاشت بر برآورد فراوانی transcript (رونوشت) تأثیر می‌گذارند.» _Genome Biology_ 21 (1): 239. <https://doi.org/10.1186/s13059-020-02151-8> .

Tonner, Peter D, Cynthia L Darnell, Barbara E Engelhardt, and Amy K Schmid. 2017. «شناسایی رشد تفاضلی جمعیت‌های میکروبی با رگرسیون فرآیند گاوسی.» _Genome Research_ 27: 320–33. <https://doi.org/10.1101/gr.210286.116> .

Townes, F. William, Stephanie C. Hicks, Martin J. Aryee, and Rafael A. Irizarry. 2019. «انتخاب ویژگی و کاهش بُعد برای RNA-Seq تک‌سلولی بر پایه یک مدل چندنومیالی.» _Genome Biology_ 20 (1): 295. <https://doi.org/10.1186/s13059-019-1861-6> .

Trapnell, Cole, David G Hendrickson, Martin Sauvageau, Loyal Goff, John L Rinn, and Lior Pachter. 2013. «تحلیل تفاضلی تنظیم ژن با دقت رونوشت (transcript (رونوشت)) با استفاده از RNA-seq.» _Nature Biotechnology_. <https://doi.org/10.1038/nbt.2450> .

Wickham, Hadley. 2009. _ggplot2_. New York, NY: Springer New York. <https://doi.org/10.1007/978-0-387-98141-3> .

Witten, Daniela M. 2011. «طبقه‌بندی و خوشه‌بندی داده‌های توالی‌یابی با استفاده از مدل پواسون.» _The Annals of Applied Statistics_ 5 (4): 2493–2518. <https://doi.org/10.1214/11-AOAS493> .

Wu, Hao, Chi Wang, and Zhijin Wu. 2013. «یک برآوردگر کوچک‌سازی جدید برای dispersion (پراکندگی)، تشخیص differential expression (تحلیل بیان تفاضلی) را در داده‌های RNA-seq بهبود می‌دهد.» _Biostatistics_ 14 (2): 232–43. <https://doi.org/10.1093/biostatistics/kxs033> .

Zhu, Anqi, Joseph G. Ibrahim, and Michael I. Love. 2018. «توزیع‌های پیشین سنگین‌دم برای داده‌های sequence count (شمارش): حذف نویز و حفظ تفاوت‌های بزرگ.» _Bioinformatics_. <https://doi.org/10.1093/bioinformatics/bty895> .
